### PR TITLE
Use System.IO.Compression.ZipArchive

### PR DESCRIPTION
**Pull request by roc916**

### CODE REVIEW

**Comment by maliming** [comment]
hi

Does this bring any benefit?

**Comment by roc916** [comment]
System.IO.Compression.ZipArchive performs better

```
using System.IO.Compression;
using ICSharpCode.SharpZipLib.Core;
using ICSharpCode.SharpZipLib.Zip;

var watch = new System.Diagnostics.Stopwatch();
watch.Start();
var outputFolder1 = @"E:\v\Acme.BookStore1\";
using (var file = File.OpenRead(@"E:\v\Acme.BookStore.zip"))
using (var zipArchive = new ZipArchive(file, ZipArchiveMode.Read))
{
    foreach (var zipEntry in zipArchive.Entries)
    {
        var fullZipToPath = Path.Combine(outputFolder1, zipEntry.FullName);
        var directoryName = Path.GetDirectoryName(fullZipToPath);

        if (!string.IsNullOrEmpty(directoryName))
        {
            Directory.CreateDirectory(directoryName);
        }

        var fileName = Path.GetFileName(fullZipToPath);
        if (fileName.Length == 0)
        {
            continue;
        }

        using (var entryStream = zipEntry.Open())
        using (var fileStream = File.Create(fullZipToPath))
        {
            entryStream.CopyTo(fileStream);
        }
    }
}

watch.Stop();
Console.WriteLine("ZipArchive: unzip time " + watch.ElapsedMilliseconds);

watch.Start();
var outputFolder2 = @"E:\v\Acme.BookStore2\";
using (var file = File.OpenRead(@"E:\v\Acme.BookStore.zip"))
{
    using (var zipInputStream = new ZipInputStream(file))
    {
        var zipEntry = zipInputStream.GetNextEntry();
        while (zipEntry != null)
        {
            var fullZipToPath = Path.Combine(outputFolder2, zipEntry.Name);
            var directoryName = Path.GetDirectoryName(fullZipToPath);

            if (!string.IsNullOrEmpty(directoryName))
            {
                Directory.CreateDirectory(directoryName);
            }

            var fileName = Path.GetFileName(fullZipToPath);
            if (fileName.Length == 0)
            {
                zipEntry = zipInputStream.GetNextEntry();
                continue;
            }

            var buffer = new byte[4096]; // 4K is optimum
            using (var streamWriter = File.Create(fullZipToPath))
            {
                StreamUtils.Copy(zipInputStream, streamWriter, buffer);
            }

            zipEntry = zipInputStream.GetNextEntry();
        }
    }
}

watch.Stop();
Console.WriteLine("SharpZipLib: unzip time " + watch.ElapsedMilliseconds);
```

```
C:/Users/roc/Desktop/ConsoleApp1/ConsoleApp1/bin/Debug/net6.0/ConsoleApp1.exe 
ZipArchive: unzip time 76
SharpZipLib: unzip time 131
```

**Comment by maliming** [comment]
hi @roc916 

Can you build a local-global tool to create the templates?

**Comment by roc916** [comment]
Yes, it works fine
```
PS D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli> dotnet run new Acme.BookStore -o "D:\BookStore\"
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Core\Volo\Abp\IAbpApplicationWithExternalServiceProvider.cs(17,20): warning CS1574: XML 注释中有未能解析的 cref 特性“serviceProvider” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Core\Volo.Abp.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Core\Volo\Abp\IAbpApplicationWithExternalServiceProvider.cs(24,20): warning CS1574: XML 注释中有未能解析的 cref 特性“serviceProvider” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Core\Volo.Abp.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.ObjectMapping\Volo\Abp\ObjectMapping\IObjectMapper.cs(14,75): warning CS1574: XML 注释中有未能解析的 cref 特性“TDestination” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.ObjectMapping\Volo.Abp.ObjectMapping.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.ObjectMapping\Volo\Abp\ObjectMapping\IObjectMapper.cs(28,46): warning CS1574: XML 注释中有未能解析的 cref 特性“destination” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.ObjectMapping\Volo.Abp.ObjectMapping.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.ObjectMapping\Volo\Abp\ObjectMapping\IObjectMapper.cs(49,75): warning CS1723: XML 注释中有引用类型参数的 cref 特性“TDestination” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.ObjectMapping\Volo.Abp.ObjectMapping.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.ObjectMapping\Volo\Abp\ObjectMapping\IObjectMapper.cs(59,46): warning CS1574: XML 注释中有未能解析的 cref 特性“destination” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.ObjectMapping\Volo.Abp.ObjectMapping.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Guids\Volo\Abp\Guids\SequentialGuidType.cs(9,75): warning CS1574: XML 注释中有未能解析的 cref 特性“ToString()” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Guids\Volo.Abp.Guids.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Guids\Volo\Abp\Guids\SequentialGuidType.cs(15,75): warning CS1574: XML 注释中有未能解析的 cref 特性“ToByteArray” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Guids\Volo.Abp.Guids.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\DependencyInjection\IAbpCommonDbContextRegistrationOptionsBuilder.cs(22,56): warning CS1574: XML 注释中有未能解析的 cref 特性“TDefaultRepositoryDbContext” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Doma
in\Volo.Abp.Ddd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\DependencyInjection\IAbpCommonDbContextRegistrationOptionsBuilder.cs(27,24): warning CS1574: XML 注释中有未能解析的 cref 特性“includeAllEntities” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo.A
bp.Ddd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\DependencyInjection\IAbpCommonDbContextRegistrationOptionsBuilder.cs(33,56): warning CS1574: XML 注释中有未能解析的 cref 特性“defaultRepositoryDbContextType” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.D
omain\Volo.Abp.Ddd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\DependencyInjection\IAbpCommonDbContextRegistrationOptionsBuilder.cs(38,24): warning CS1574: XML 注释中有未能解析的 cref 特性“includeAllEntities” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo.A
bp.Ddd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Auditing\AuditedAggregateRootWithUser.cs(7,64): warning CS1574: XML 注释中有未能解析的 cref 特性“IAuditedObjectObject{TUser}” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo.Abp.D
dd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Auditing\AuditedAggregateRootWithUser.cs(22,64): warning CS1574: XML 注释中有未能解析的 cref 特性“IAuditedObjectObject{TUser}” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo.Abp.
Ddd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Auditing\CreationAuditedAggregateRootWithUser.cs(7,64): warning CS1574: XML 注释中有未能解析的 cref 特性“ICreationAuditedObjectObject{TCreator}” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Dd
d.Domain\Volo.Abp.Ddd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Auditing\CreationAuditedAggregateRootWithUser.cs(18,64): warning CS1574: XML 注释中有未能解析的 cref 特性“ICreationAuditedObjectObject{TCreator}” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.D
dd.Domain\Volo.Abp.Ddd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Auditing\CreationAuditedEntityWithUser.cs(18,64): warning CS1574: XML 注释中有未能解析的 cref 特性“ICreationAuditedObjectObject{TCreator}” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Doma
in\Volo.Abp.Ddd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo\Abp\Domain\Entities\Auditing\FullAuditedEntityWithUser.cs(25,27): warning CS1574: XML 注释中有未能解析的 cref 特性“IFullAuditedObjectObject{TUser}” [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Ddd.Domain\Volo.Abp
.Ddd.Domain.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\TranslateCommand.cs(258,26): warning CS0168: 声明了变量“e”，但从未使用过 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NugetPackageToLocalReferenceConverter.cs(15,23): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(..
.)" 在后台线程上执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\AngularSourceCodeAdder.cs(69,24): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程
上执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\AngularSourceCodeAdder.cs(119,24): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程
上执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs(104,17): warning CS4014: 由于此调用不会等待，因此在此调用完成之前将会继续执行当前方法。请考虑将 "await" 运算符应用于调用结果。 [D:\GitHub\abpzone\abp\framework\src\Vol
o.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\AngularSourceCodeAdder.cs(141,24): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程
上执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionFileModifier.cs(13,23): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程上
执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\ProjectNugetPackageAdder.cs(261,17): warning CS4014: 由于此调用不会等待，因此在此调用完成之前将会继续执行当前方法。请考虑将 "await" 运算符应用于调用结果。 [D:\GitHub\abpzone\abp\framework\s
rc\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\ProjectNugetPackageAdder.cs(265,17): warning CS4014: 由于此调用不会等待，因此在此调用完成之前将会继续执行当前方法。请考虑将 "await" 运算符应用于调用结果。 [D:\GitHub\abpzone\abp\framework\s
rc\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\ProjectNugetPackageAdder.cs(293,30): warning CS0168: 声明了变量“e”，但从未使用过 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\AngularSourceCodeAdder.cs(232,38): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程
上执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\AngularSourceCodeAdder.cs(298,32): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程
上执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionFileModifier.cs(188,32): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程上
执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs(290,13): warning CS4014: 由于此调用不会等待，因此在此调用完成之前将会继续执行当前方法。请考虑将 "await" 运算符应用于调用结果。 [D:\GitHub\abpzone\abp\framework\src\Vo
lo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\ProjectCreationCommandBase.cs(228,9): warning CS0162: 检测到无法访问的代码 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs(301,38): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程上
执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs(325,38): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程上
执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Templates\App\AppNoLayersTemplateBase.cs(81,17): warning CS0162: 检测到无法访问的代码 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs(802,40): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程上
执行占用大量 CPU 的工作。 [D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli.Core\Volo.Abp.Cli.Core.csproj]
[20:36:52 INF] ABP CLI (https://abp.io)
[20:36:52 INF] Creating your project...
[20:36:52 INF] Project name: Acme.BookStore
[20:36:52 INF] Output folder: D:\BookStore\
[20:36:55 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Application
[20:36:56 INF] 'Acme.BookStore' has been successfully created to 'D:\BookStore\'
[20:36:56 INF] Installing client-side packages...
[20:36:57 INF] Found 1 projects.
[20:36:57 INF] D:\BookStore\src\Acme.BookStore.Web
[20:36:58 INF] Running Yarn on D:\BookStore\src\Acme.BookStore.Web
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@abp/aspnetcore.mvc.ui.theme.basic > @abp/aspnetcore.mvc.ui.theme.shared > @abp/bootstrap > bootstrap@5.1.3" has unmet peer dependency "@popperjs/core@^2.10.2".
warning "@abp/aspnetcore.mvc.ui.theme.basic > @abp/aspnetcore.mvc.ui.theme.shared > @abp/jquery-validation-unobtrusive > @abp/jquery-validation > jquery-validation@1.19.3" has unmet peer dependency "jquery@^1.7 || ^2.0 || ^3.1".
[4/4] Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.22.18", while you're on "1.22.17".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
Done in 13.65s.
PS D:\GitHub\abpzone\abp\framework\src\Volo.Abp.Cli>

```

image

**Comment by maliming** [comment]
Thanks

**Comment by roc916** [comment]
Fix `zipEntry.FullName` prefixed with `'/'`, so Path.Combine is not as expected.(https://github.com/abpframework/abp/pull/12181/commits/a71b043955c3671e17bb45693eaf56f4c2a79b38)

img

---

Create angular template with local cli tool.

```
D:\>abp new BookStore -o "D:\\BookStore" -u angular
[20:30:28 INF] ABP CLI (https://abp.io)
[20:30:28 INF] Version 5.3.0 (Stable)
[20:30:29 INF] Creating your project...
[20:30:29 INF] Project name: BookStore
[20:30:29 INF] UI Framework: Angular
[20:30:29 INF] Output folder: D:\BookStore
[20:30:31 INF] Using cached template: app, version: 5.2.1
[20:30:31 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Application
[20:30:32 INF] 'BookStore' has been successfully created to 'D:\BookStore'
[20:30:32 INF] Installing client-side packages...
[20:30:33 INF] Found 2 projects.
[20:30:33 INF] D:\BookStore\angular
[20:30:33 INF] D:\BookStore\aspnet-core\src\BookStore.HttpApi.Host
[20:30:34 INF] Running Yarn on D:\BookStore\angular
```

image

**Pull request closed without merging**
