### PR TITLE
Feature/modify modules constants

### PR DESCRIPTION
**Pull request by Fisher-Joe**
Move connection string names to constants for modules. 
#1332 is done.

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks, you're great :)

**Comment by maliming** [comment]
There is no problem with the code.
Just don't know if the constant should be placed in the Domain or in the Domain.Shared layer.

**Comment by Fisher-Joe** [comment]
@maliming
I see,do I have to re PR?

**Comment by maliming** [comment]
@Fisher-Joe 
No, it just makes the PR clearer.

**Comment by Fisher-Joe** [comment]
@maliming 
Ok, I will pay attention next time.

**Pull request merged**
