### PR TITLE
Update Getting-Started-AspNetCore-Application.md

### PR DESCRIPTION
**Pull request by pasestars**
Add builder.Services.ReplaceConfiguration(builder.Configuration);

### CODE REVIEW

**Comment by maliming** [comment]
hi

The `AddApplicationAsync` method already did this.

https://github.com/abpframework/abp/blob/rel-5.3/framework/src/Volo.Abp.AspNetCore/Microsoft/Extensions/DependencyInjection/WebApplicationBuilderExtensions.cs#L19

**Comment by pasestars** [comment]
I use from this in Program.cs and had an error.
image
image

**Comment by maliming** [comment]
Please use the extension method of `WebApplicationBuilder`.

**Comment by pasestars** [comment]
But in this example do that, and in doc had an error.
image
I just follow this [tutorial](https://docs.abp.io/en/abp/latest/Getting-Started-AspNetCore-Application)

**Comment by maliming** [comment]
We will check and update the samples and documents.

**Comment by maliming** [comment]
Move to https://github.com/abpframework/abp/pull/13289

**Pull request closed without merging**
