### PR TITLE
Change AbpLazyServiceProvider lifetime to scoped.

### LINKED ISSUE #7227: Change AbpLazyServiceProvider DI lifetime to IScopedDependency?
Abp `AbpLazyServiceProvider` has a transient dependency, which if I understand correctly means that each service injected in a request gets a new instance? Would it be better to make it scoped so that the `CachedServices` can be used by all services for each request? Forgive me if I have misunderstood the mechanisms of DI.

https://github.com/abpframework/abp/blob/34d66ee70f6d2bf719c251331bbf1eda086960c3/framework/src/Volo.Abp.Core/Volo/Abp/DependencyInjection/AbpLazyServiceProvider.cs#L7-L8

### PR DESCRIPTION
**Pull request by maliming**
Resolve #7227

### CODE REVIEW

**Comment by jerviscui** [comment]
I have a question.
Just like the following code.

If `IAbpLazyServiceProvider` is `IScopedDependency`, the `Baby` life will be changed to scope  and is no longer transient.
Am I right?

```csharp
public class Baby : ITransientDependency
{
}

public class ServiceA : ITransientDependency
{
    public IAbpLazyServiceProvider AbpLazyServiceProvider { get; set; }

    public Baby Baby => AbpLazyServiceProvider.LazyGetRequiredService<Baby>();
}

public class ServiceB : ITransientDependency
{
    public IAbpLazyServiceProvider AbpLazyServiceProvider { get; set; }

    public Baby Baby => AbpLazyServiceProvider.LazyGetRequiredService<Baby>();
}

public class MainA
{
    void Test()
    {
        var aBaby = new ServiceA().Baby;
        var bBaby = new ServiceB().Baby;
    }
}
```

**Comment by hikalkan** [comment]
I am unsure about that and need to think detailed if we have problems (like memory leak), especially if the current scope is not HttpContext.

**Comment by hikalkan** [comment]
>If IAbpLazyServiceProvider is IScopedDependency, the Baby life will be changed to scope and is no longer transient.
Am I right?

Yes, this PR makes that (while your sample is not complete, I assume you are resolving all instance in the same scope).

**Comment by maliming** [comment]
Move to backlog.

**Pull request closed without merging**
