### PR TITLE
Call ConfigureAwait(false) on all library related await calls

### PR DESCRIPTION
**Pull request by javiercampos**
Related to #2497 

Only added the `ConfigureAwait(false)` calls on library solutions (all Volo.Abp.* solutions).

All tests pass except for 1 but doesn't seem related to this. The failing one is:
`Volo.Abp.Emailing.EmailTemplateStore_Tests.Should_Get_Registered_Template_With_Layout`

Which fails with:

```
   Shouldly.ShouldAssertException : template.Content
    should contain (case insensitive comparison)
"<body>
    Please confirm your email address by clicking the link below."
    but was actually
"<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
```

Doesn't seem related to any of these commits and should probably be fixed separately

### CODE REVIEW

**Comment by javiercampos** [comment]
All commits are 1 per solution (except the fixing one, which the analyzer couldn't figure out correctly)

**Comment by hikalkan** [comment]
That's a great contribution. Thank you for your huge effort.

**Comment by maliming** [comment]
@mehmetuken mentioned a https://github.com/Fody/ConfigureAwait class library. It can save a lot of code. I haven't tried it, but from the introduction, it really is.

**Comment by javiercampos** [comment]
@maliming adding Fody to the build pipeline might be painful... when it works, it works fine: when it doesn't, you'll want to pull all your hairs off... I'd GREATLY recommend **AGAINST** it for a library. I find it more than ok for app code (I've used it in the past for many things), but not for a library :-)

**Comment by hikalkan** [comment]
@maliming  Fody seems good, yes, but I also think to not add a new dependency for now. I will merge this PR and delay the Fody decision.

**Pull request merged**
