### PR TITLE
Upgrade to NET 5.0 RC.

### LINKED ISSUE #5676: Upgrade to .NET 5.0 rc1
We want to move all the framework, modules, themes... to .NET 5.0 in a branch to see if we have any problem. If everything goes well, we can make this movement early (considering to skip the ABP version 3.3 and merge it to the version 4.0, then publish early previews).

### PR DESCRIPTION
**Pull request by maliming**
Resolve #5676

#### RC 1

1. Change `TargetFramework` (`framework`.`modules`,`templates`).:
      1. Change `netcoreapp3.1` to `net5.0` for all projects.
      2. Change `netstandard2.0` to `netstandard2.1` for all EF Core projects.
      3. Change `netstandard2.1` to `net5.0` for all Blazor projects.
2. Update `Microsoft.*` package from `3.x` to `5.0.0-rc.1.*` for all projects.
3. Remove `framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/DatabaseFacadeExtensions.cs`, It's already exist in EF Core 5.0
4. Remove obsolete `WithCulture` method in the `framework/src/Volo.Abp.Localization/Volo/Abp/Localization/AbpDictionaryBasedStringLocalizer.cs`.
5. Remove `framework/src/Volo.Abp.Serialization/Volo/Abp/Serialization/Binary/BinarySerializationHelper.cs` and use `System.Text.Json.JsonSerializer` instead. https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide
6. Comment all the code in the `Oracle.EntityFrameworkCore` and `Pomelo.EntityFrameworkCore.MySql` packages. It's Incompatible with the new EF Core 5.0(https://github.com/oracle/dotnet-db-samples/issues/81 https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088)
7. Update `ContentTypeMaps` in `framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/VirtualFileSystem/AbpAspNetCoreContentOptions.cs`, Copy from https://github.com/dotnet/aspnetcore/blob/v5.0.0-rc.1.20451.17/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs#L22
8. Update some unit test methods because `DateTime values are model bound as UTC times`(https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-3.1&tabs=visual-studio#changes-to-model-binding-in-aspnet-core-mvc-and-razor-pages)
9. Remove `Microsoft.AspNetCore.Components.WebAssembly.Build` packages form blazor project.
10. Use `<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">` for blazor projects.
11. Add `AsyncStateMachineAttribute `to the `AttributesToAvoidReplicating `of **Castle DynamicProxy** in the blazor project. (https://github.com/abpframework/abp/blob/maliming/net5/framework/src/Volo.Abp.AspNetCore.Components.WebAssembly/Microsoft/AspNetCore/Components/WebAssembly/Hosting/AbpWebAssemblyHostBuilderExtensions.cs#L25-L29)
12. Comment the `MySQL` and `Oracle` packages, they do not support .NET 5 now. See No.6.

#### RC 2

1. Update `Microsoft.*` package from `5.0.0-rc.1` to `5.0.0-rc.2*` for all projects.
2. Use preview packages of **Blazorise**.
3. Set `BlazorWebAssemblyLoadAllGlobalizationData `in the blazor project(https://github.com/dotnet/aspnetcore/pull/26192).
4. Use split queries for some `include` query. (https://docs.microsoft.com/en-us/ef/core/querying/related-data/eager#single-and-split-queries)

### CODE REVIEW

**Comment by maliming** [comment]
Identity Server is no problem.

**Comment by realLiangshiwei** [comment]
I tested the startup template, MVC UI and Angular UI it works fine. but blazor UI is not working.  @stsrki Could you check this? 

image

**Comment by stsrki** [comment]
@realLiangshiwei Check that you have `<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">` in Blazor WebAssembly .csproj file. Instead of `<Project Sdk="Microsoft.NET.Sdk.Web">`

**Review by realLiangshiwei — APPROVED** [review]

**Pull request merged**
