### PR TITLE
Configure virtual files for app templates

### PR DESCRIPTION
**Pull request by liangshiw**
Resolve https://github.com/abpframework/abp/issues/4110

### CODE REVIEW

**Comment by hikalkan** [comment]
Why we need to this, can you explain please?

**Comment by liangshiw** [comment]
[Custom user interface documentation](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface) introduce how to replace existing module pages, but some developers get some problems according to the documentation:  https://github.com/abpframework/abp/issues/3766 https://github.com/abpframework/abp/issues/3987.
We should pre-configure the template.

**Comment by hikalkan** [comment]
Normally, physical files overrides embedded files. I suppose when we publish the application, physical files are not in the published path (since they are probably pre-compiled). So, this PR would be helpful for such a case. I am just curious about changing the default behaviour of AspNet Core.
I will think on that. Thanks.

**Comment by hikalkan** [comment]
I support this problem will be solved by https://github.com/abpframework/abp/pull/4016

I am still working on...

**Comment by hikalkan** [comment]
I am canceling this since we already canceled VFS usage for module razor files: https://github.com/abpframework/abp/pull/4016
So, no need to this, everything should work as expected.

**Pull request closed without merging**
