### PR TITLE
Set the first tab active after search in permissions

### PR DESCRIPTION
**Pull request by enisn**
### Description

Resolves https://github.com/volosoft/volo/issues/18704
Resolves https://github.com/volosoft/volo/issues/18703

permissions-search

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Please describe how this can be tested by the test engineers if it is not already explicit - or remove this section if no need to description.

### CODE REVIEW

**Review by oykuermann — CHANGES_REQUESTED** [review]
When I write open, it cannot find OpenId:
image

**Comment by oykuermann** [comment]
- [ ] After filtering & pressing 'Grant all permissions', I expect to see only filtering items to be selected. 

[screencast-localhost_44318-2024_10_23-17_20_54.webm](https://github.com/user-attachments/assets/24d1fbaf-45d7-4e0c-82fe-2ec1553f4fbb)

I asked this, and this is how it should work

**Comment by enisn** [comment]
> When I write open, it cannot find OpenId: image

I cannot reproduce this issue. It's probably related to your browser language. In Turkish I and i are differently compared

**Comment by enisn** [comment]
> * [ ]  After filtering & pressing 'Grant all permissions', I expect to see only filtering items to be selected.
> 
>  screencast-localhost_44318-2024_10_23-17_20_54.webm 
> I asked this, and this is how it should work

It's a new feature and requires bigger changes, you can create a new issue as **feature** for this

**Comment by oykuermann** [comment]
I tried openI openi openı and openİ, none of them is worked :( 

https://github.com/user-attachments/assets/d264a815-dac0-401a-aae3-0badbefc8212



> > When I write open, it cannot find OpenId: image
> 
> I cannot reproduce this issue. It's probably related to your browser language. In Turkish I and i are differently compared

**Review by oykuermann — APPROVED** [review]

**Pull request merged**
