### PR TITLE
Update the contents of common.ps1 to the latest.

### LINKED ISSUE #1471: Nightly packages lost : Volo.Abp.Account.HttpApi
Hi, I am trying to use nightly builds, but when I restore the packages I got an error: Cannot find Volo.Abp.Account.HttpApi (0.19.0-preview20190711). I think it's missing. (●'◡'●)

### PR DESCRIPTION
**Pull request by maliming**
Resolve #1471

### CODE REVIEW

**Comment by hikalkan** [comment]
@maliming did you re-order lines? why? It is not hard for me to review it. Are you sure that it is correct?

**Comment by hikalkan** [comment]
I am merging it.

**Comment by maliming** [comment]
I use the file lookup tool to regenerate frames and modules. Find all csproj files in the src folder. This tool has a sort by default.

**Comment by hikalkan** [comment]
Hmmm... I suppose this works but I am not sure if we publish all projects in the src folders. Since this is critic, can you double check it? Thanks for your time.

**Comment by maliming** [comment]
Ok, I will confirm it again.

**Comment by maliming** [comment]
Has been confirmed again, no problem.

**Comment by hikalkan** [comment]
Thanks @maliming ;)

**Pull request merged**
