### PR TITLE
Add extra enumeration large size to bootstrap modal

### PR DESCRIPTION
**Pull request by viewtance**

### CODE REVIEW

**Comment by maliming** [comment]
```
SM (small)
MD (medium) 
LG (large)
XL (extra-large)
```
https://github.com/twbs/bootstrap/blob/v4.4.1/scss/_variables.scss#L972-L975

**Comment by viewtance** [comment]
Thanks for your approval@maliming

**Comment by maliming** [comment]
@viewtance Why did you close and delete it?

**Comment by viewtance** [comment]
Why not merged into 2.2 milestone?

**Pull request merged**
