### PR TITLE
Move all projects to generic host & remove IConfigurationAccessor usage.

### LINKED ISSUE #1094: Configuration redesign
- [x] Remove `IConfigurationAccessor`. Use `IConfiguration` instead. This requires to use the generic host on host builder instead of old style coding #391
- [x] Crate & Register `IConfiguration` if not registered before.
- [x] Update all usages in all projects

### LINKED ISSUE #1888: Move all projects to generic host & remove IConfigurationAccessor usage
* How to move to generic host: https://github.com/abpframework/abp/issues/391#issuecomment-540669420
* Use IConfiguration instead of IConfigurationAccessor https://github.com/abpframework/abp/issues/1094

### PR DESCRIPTION
**Pull request by maliming**
This resolve #1888 , resolve #1094

Refactoring `AbpAspNetCoreIntegratedTestBase` based on generic WebHost 

https://github.com/abpframework/abp/pull/1894/files#diff-2bdeefcb05a7d19d5c4233f0ebc10c12R24

### CODE REVIEW

**Comment by maliming** [comment]
Found a unit test failed, is being resolved

**Comment by maliming** [comment]
hi @hikalkan 
The current situation is that we can't get `IConfiguration` under the module's `ConfigureServices` method.

Currently using the following method to get `IConfiguration`, but this will be out of date.
```
var configuration = context.Services.BuildConfiguration();
```

Although can inject `IConfiguration` in the `Startup` class, this can't be integrated with abp.

**Comment by hikalkan** [comment]
Can you try this in ConfigureServices: `context.Services.GetSingletonInstance<IConfiguration>()`

**Comment by maliming** [comment]
Actually I tried. I can't get `IConfiguration` or `IConfigurationRoot` like `IWebHostEnvironment`.

```
Could not find singleton service: Microsoft.Extensions.Configuration.IConfiguration, Microsoft.Extensions.Configuration.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60

Could not find singleton service: Microsoft.Extensions.Configuration.IConfigurationRoot, Microsoft.Extensions.Configuration.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```

**Comment by hikalkan** [comment]
OK, let me check this.

**Comment by hikalkan** [comment]
````csharp
var config = context.Services.GetSingletonInstanceOrNull<HostBuilderContext>().Configuration
````

should work. I changed services.GetConfiguration() to use the code above (see https://github.com/abpframework/abp/commit/0f24054c6af36a2b75ebfdb74be7a581d8c1fe83), so you can use context.Services.GetConfiguration() just like before in ConfigureServices method.

Merge dev to your branch to be able to use it.

**Comment by maliming** [comment]
All done.

**Pull request merged**
