### PR TITLE
Add option to disable service bus

### PR DESCRIPTION
**Pull request by wocar**
The main reason for these changes is integration testing

### CODE REVIEW

**Comment by maliming** [comment]
Thanks @wocar

**Review by maliming — APPROVED** [review]

**Comment by maliming** [comment]
hi @wocar 

Are you interested in abstracting this disable/enable option?

So other providers (RabbitMQ, Kafka) will also support this feature

**Comment by rqx110** [comment]
how about rename `IsServiceBusDisabled` to `Disabled` or `IsDisabled`? @maliming

**Comment by maliming** [comment]
> how about rename `IsServiceBusDisabled` to `Disabled` or `IsDisabled`? @maliming

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BackgroundJobs.Abstractions/Volo/Abp/BackgroundJobs/AbpBackgroundJobOptions.cs#L15

**Comment by wocar** [comment]
Yeah I followed that naming convention.

**Comment by wocar** [comment]
So I'm not quite sure where should we abstract this?

My problem is that when im using WebApplicationFactory to do integration testing, the Azure service actually gets initialized. 

Maybe it is just better to add a property to each `Options` class in every module?

**Comment by wocar** [comment]
@maliming

**Review by maliming — APPROVED** [review]

**Comment by maliming** [comment]
ok, Merged. Thanks again.

**Pull request merged**
