### PR TITLE
AutoFilterer implementation

### PR DESCRIPTION
**Pull request by enisn**
## Summary
This PR includes [AutoFilterer](https://github.com/enisn/AutoFilterer) implementation as extension for ABP Framework.

## Blocks
- #6157 blocks to merge this PR
- See **Discussion** section at the bottom of description

## Changes
- Added `Volo.Abp.AutoFilterer` _Class Library_
- Added `Volo.Abp.AutoFilterer.Tests` _xUnit Test Class Library_ 
- Added `AutoFilterer.md` _(Set-up & Usage Documentation)_

## Usage 
See last state of '[/en/AutoFilterer.md](/abpframework/abp/pull/6158/files#diff-29106afe3ebb8d01de959bb4b1c344a67ece462ef210ece9604161a6c3fcfb59)'

## Discussion
I'm not sure which other features uses following methods in `CrudAppService`:
- ApplyPaging(), ApplySorting(), ApplyDefaultSorting()

I thought, I can't change core class of project, so I created a new class which is named as `CrudAutoFiltererAppService` to override these methods. I'm not sure it's right way or not 🤔. Changing inherited type is kind of difficult implementation and mistakable.

I'm open any suggestions

### CODE REVIEW

**Comment by maliming** [comment]
Thanks @enisn

**Comment by hikalkan** [comment]
Thanks @enisn I will review this in the next days.

**Comment by enisn** [comment]
I realized that, this PR breaks auto-sorting from javascript. I'll work on it.

**Comment by enisn** [comment]
Still missing tests for newly added `AbpPaginationFilterBase` type.

**Review by furkandeveloper — APPROVED** [review]
Approved.

**Comment by hikalkan** [comment]
First impression is pretty fine. I will test this and think more on the design.

**Comment by enisn** [comment]
I've fixed all design problems. Now, built-in client features all works as same with abp default. 👍 _(data-tables etc.)_

---

Still problem with ComplexTypes which is related with #6157

**Comment by enisn** [comment]
Covered with Integration tests. Ready to review now 🚀

**Comment by murat-yuceer** [comment]
will you add document for that abp site

**Comment by hikalkan** [comment]
We are not sure to include this to the framework yet. If we include, yes, it will be documented.

**Comment by enisn** [comment]
It's not a good implementation for all use-cases. I've marked as draft for now.

**Comment by muratyuceer** [comment]
you can use https://github.com/DevExpress/DevExtreme.AspNet.Data , i implemented it for blazorise grid.
Basicly its have query standart for select,order,where,group,summary
On server side its apply that query to IQuarable object for us (modify&create Expressions)

**Comment by mehmetuken** [comment]
Hi @enisn, can you publish this package outsource module ?

**Pull request closed without merging**
