### PR TITLE
Angular - Permission Tree Selection Hierarchical Fix

### LINKED ISSUE #20505: Deselecting Permissions in TreeComponent-Permissions modal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Theme: LeptonX

If you deselect an Permission inside the Permissions-Modal, that has multiple hierarchical child permissions (e.g. User Management), only the first children gets deselected.

chrome-capture-2024-7-14 (1)

### Reproduction Steps

- Default Installation without changes (LeptonX-Theme)

### Expected behavior

All child permissions and their children (recursive) should get deselected

### Actual behavior

Only the first set of child permissions get deselected.

### Regression?

_No response_

### Known Workarounds

_No response_

### Version

8.2.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sumeyyeKurtulus**
### Description

Resolves #20505

Here is a record showing the related fix
PermissionTree

### Checklist

- [X] I fully tested it as developer / designer and created unit / integration tests

### How to test it?

- You can copy the changes to the template modules and test any modal that has permission selection as can be seen in the video.

### CODE REVIEW

**Review by oykuermann — CHANGES_REQUESTED** [review]
- [x] If user selects a main permission, sub-permission should not be selected. The main permissions are the permission to view related pages.

 

- [x] If user selects a sub-permission, main permission should be selected.

 

- [x] If user deselects the main permission, sub-permissions should be deselected.

 

- [x] If user deselects the sub-permission, main permissions should not deselect.

image

**Comment by oykuermann** [comment]
MVC:

[screencast-localhost_44357-2024.08.webm](https://github.com/user-attachments/assets/e7d5c015-c101-4845-b078-a58c014ea940)

**Comment by masum-ulu** [comment]
@sumeyyeKurtulus it shouldn't select all child permission when the select root like `User management` checkbox in tree. It must be like MVC example

**Comment by sumeyyeKurtulus** [comment]
> @sumeyyeKurtulus it shouldn't select all child permission when the select root like `User management` checkbox in tree. It must be like MVC example

If you mean that selecting `Edit` should not also select the `User Management` permission, this would break the parent selection in the second item above.

**Review by masum-ulu — APPROVED** [review]

**Review by oykuermann — CHANGES_REQUESTED** [review]
I'll check after changes:
image

**Review by oykuermann — APPROVED** [review]

**Pull request merged**
