### PR TITLE
Wrong polish culture code in translation file name

### PR DESCRIPTION
**Pull request by CrazyBaran**
Culture code for polish is pl-PL.

### CODE REVIEW

**Comment by maliming** [comment]
Currently all projects are using `pl.json`

```json
{
  "culture": "pl",
  "texts": {

  }
}
```

**Comment by CrazyBaran** [comment]
So it is breaking change?

**Comment by maliming** [comment]
image

**Comment by CrazyBaran** [comment]
You exlude test in this search, don't change it in tests or make push for them also?

**Comment by maliming** [comment]
I forgot to unexclude the folder.

image

**Comment by CrazyBaran** [comment]
Ok, so all files allign.

**Comment by maliming** [comment]
I think this is a breaking change.

**Comment by hikalkan** [comment]
Why not `pl-PL`, and not `pl`?
As you know, `pl-PL` (and actually all `pl-*`) fallbacks to `pl`, so `pl` covers more.
We prefer `pl` unless there are multiple `pl` accents.

**Comment by CrazyBaran** [comment]
Well I think it is good practice to keep everything in one convention. Not mixing up pl alone with en-US for example. Anyway if you look into polish documentation on microsoft they also used pl-pl.

**Comment by hikalkan** [comment]
@maliming I agree this is a breaking change, but it is very minor and easy to fix for existing applications. If they've used `pl`, they need to switch to `pl-PL`. Since `pl-PL` seems the only valid value (there is no other `pl-x`), this way seems better. I marked it as breaking change to get attention.

**Pull request merged**
