### PR TITLE
Add `GoogleTranslation` feature to Docs module.

### LINKED ISSUE #20179: Add Google translation to Docs module.

### PR DESCRIPTION
**Pull request by maliming**
Resolves #20179

image

image

image

### CODE REVIEW

**Review by enisn — APPROVED** [review]

**Review by armgnunlu — COMMENTED** [review]
Can you place it like this? It has the same style as the other selectboxes.
image

**Comment by enisn** [comment]
@armgnunlu What about "Powered by Google Translate" attribution text?
It has to be there legally: https://cloud.google.com/translate/attribution#attribution_and_logos

image

**Comment by armgnunlu** [comment]
image

it would be good if you can place it like this.

**Comment by armgnunlu** [comment]
image

If the previous option is difficult, you can try this one.

**Comment by maliming** [comment]
hi @armgnunlu @enisn 

I have pushed the new changes. Please feel free to review it again. Thanks

image

**Comment by maliming** [comment]
image

**Pull request merged**
