### PR TITLE
Make AuthWrapperComponent replacable in account module

### LINKED ISSUE #7989: Make AuthWrapperComponent replacable in account module
Account module is coming back after #7842 is merged. 
Currently, all components are replacable in account module, except for `AuthWrapperComponent`.
I think it should be replacable too.
```typescript
{
  path: '',
  component: ReplaceableRouteContainerComponent,
  data: {
    replaceableComponent: {
      key: eAccountComponents.AuthWrapper,
      defaultComponent: AuthWrapperComponent,
    } as ReplaceableComponents.RouteData<AuthWrapperComponent>,
  },
}
```

### PR DESCRIPTION
**Pull request by mtozlu**
Resolves #7989 
Maybe merged after #7861

### CODE REVIEW

**Comment by realLiangshiwei** [comment]
Hi,

Thanks for your contributor, but your PR contains too many unwanted commits. could you send a new PR? thanks.

image

**Comment by mtozlu** [comment]
@realLiangshiwei Thanks for the review. The commits are not unwanted. This feature is branched from `feat/volo-5292` because account module came back with that branch (it was deleted before). And the change i made is in account module.
So this PR can be merged after #7861 is merged. After #7861 is merged, this PR will contain a single commit.

**Comment by realLiangshiwei** [comment]
Thanks for explanation. 
waiting for https://github.com/abpframework/abp/pull/7861 merged

**Comment by mehmet-erim** [comment]
Hi @mtozlu 

 #7861 is merged. But still showing many changes.

**Comment by mtozlu** [comment]
@mehmet-erim Thanks for the info. 
It's clean now.

**Review by mehmet-erim — APPROVED** [review]

**Comment by mehmet-erim** [comment]
Thanks for the contribution 🙂

**Pull request merged**
