### PR TITLE
Add docs module client proxies

### PR DESCRIPTION
**Pull request by zhishile**
Solve the problem that the document module cannot be used under the Tired solution.

### CODE REVIEW

**Comment by maliming** [comment]
hi @zhishile 

Can you merge from **dev** branch? Because the action failed.

**Comment by zhishile** [comment]
Try commit again.Local compilation successful,but **github-actions check failure**.
I can't see the specific error message.Please give me a hint. @maliming

**Comment by maliming** [comment]
Merge dev branch(`abpframework:dev`) into your branch(`zhishile:dev`).

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/3986

**Pull request closed without merging**
