### PR TITLE
Fix #5556.

### LINKED ISSUE #5556: Docs module: Parametric pages doesn't work well with mobile safari
Parametric pages doesn't work well with mobile safari

Go to the page https://docs.abp.io/en/abp/3.2/Tutorials/Part-1?UI=Blazor&DB=EF and click the the next page. It switches back to MVC.

### PR DESCRIPTION
**Pull request by mehmetuken**
Fix #5556.

This bug have all browsers because user coming directly sections selected url cookie is empty and page change we don't now which sections selected. Cookie is empty set or query string have any value set cookie again.

### CODE REVIEW

**Comment by yekalkan** [comment]
> This bug have all browsers

Do you mean mobile browsers? We are sure that it works on computers. 
Also, i tested on google chrome (android) and it worked there as well.

Problem is specific to Safari Mobile (IOS) and i don't think this PR will fix it. Have you tested this on Safari Mobile?

**Comment by mehmetuken** [comment]
> > This bug have all browsers
> 
> Do you mean mobile browsers? We are sure that it works on computers.
> Also, i tested on google chrome (android) and it worked there as well.
> 
> Problem is specific to Safari Mobile (IOS) and i don't think this PR will fix it. Have you tested this on Safari Mobile?

Are you sure ?  My setup is
MacOS Catalina 10.15.7
Chrome 87.0.4280.88 (Official Build) (x86_64)

docs-test

**Comment by yekalkan** [comment]
@mehmetuken I asked a Mac user colleague and he confirmed your issue. But i don't have any problem on my Windows installed machine and android installed mobile phone.

Do these changes fixed it for you? (local test)

**Comment by mehmetuken** [comment]
This bug not related os all browser have this bug. I can't run docs module local but this solution correct because you click url cookies not set new parameter. Clean cookies and try again.


This test from windows 10 and chrome. I was selected angular ui before.

ux6GzqJwIZ

**Comment by yekalkan** [comment]
> This bug not related os all browser have this bug. I can't run docs module local but this solution correct because you click url cookies not set new parameter. Clean cookies and try again.

I cleaned cookies, then even used Incognito mode but it still works.

Anyway, i'm merging this since there are other folks reproducing this issue.

**Pull request merged**
