### PR TITLE
feat: user can set a variable on the environment without extending

### PR DESCRIPTION
**Pull request by mahmut-gundogdu**
suggestion to  #11950

### CODE REVIEW

**Comment by rqx110** [comment]
why not just:
```ts
[key:string]: any;
```
instead of
```ts
customSettings?:{ 
    [key:string]: any;
  }
```

**Comment by mahmut-gundogdu** [comment]
> why not just:
> 
> ```ts
> [key:string]: any;
> ```
> 
> instead of
> 
> ```ts
> customSettings?:{ 
>     [key:string]: any;
>   }
> ```

because I thought grouping the custom settings was a "good idea." but yes, we can add root

**Comment by rqx110** [comment]
in my opnion, with `[key:string]: any;`, the end developer can define their favorite key(group) name. leave options to developer is better.

**Comment by mahmut-gundogdu** [comment]
> in my opnion, with `[key:string]: any;`, the end developer can define their favorite key(group) name. leave options to developer is better.

Yes, you are right. It is a better idea. I am converting. Thank you for your feedback.

**Comment by mahmut-gundogdu** [comment]
> in my opnion, with `[key:string]: any;`, the end developer can define their favorite key(group) name. leave options to developer is better.

What do you think "any vs unknown" in this case?

`[key: string]: unknown;
`
or 
`[key: string]: any;
`
I thought any is  (a little bit) 'unsafe'

**Comment by rqx110** [comment]
> What do you think "any vs unknown" in this case?

sorry, I have no idea on this

**Review by muhammedaltug — APPROVED** [review]

**Pull request closed without merging**
