### PR TITLE
Audited*WithUser generic type wrong constraint.

### LINKED ISSUE #2624: FullAuditedAggregateRootWithUser generic type wrong constraint
Anyone please tell me why FullAuditedAggregateRootWithUser need TUser to inherited from IEntity\<long\> while IUser interface using IEntity\<Guid\>?
https://github.com/abpframework/abp/blob/654eeede81a733382066bfd00ab19b6b65ceec0e/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Auditing/FullAuditedAggregateRootWithUser.cs#L11-L12

https://github.com/abpframework/abp/blob/654eeede81a733382066bfd00ab19b6b65ceec0e/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Auditing/FullAuditedAggregateRootWithUser.cs#L30-L31

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/users/src/Volo.Abp.Users.Domain/Volo/Abp/Users/IUser.cs#L8

### PR DESCRIPTION
**Pull request by maliming**
Resolve #2624

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks @maliming :)

**Comment by xkaede** [comment]
hi @maliming 
Would you please make the properties of Audited*WithUser as virtual.Some of them are not virtual.
eg.
https://github.com/abpframework/abp/blob/40bc8e3cc1697a3e88b7dd61f849c705755eb76d/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Auditing/FullAuditedEntityWithUser.cs#L18

**Comment by maliming** [comment]
hi @xkaede https://github.com/abpframework/abp/commit/a7d5cba4ddcab3fa77064756bf92bc21b5b78718

**Comment by xkaede** [comment]
Thanks @maliming

**Pull request merged**
