### PR TITLE
CancellationToken parameter added for background jobs

### LINKED ISSUE #15281: Background jobs not take `CancellationToken` parameter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We should be able to cancel background job if it's supported.
Hangfire in 'Processing' tab we can delete when it's running but this time it's still working in the background.

### Reproduction Steps

- Using hangfire integration package for [background worker](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.BackgroundWorkers.Hangfire) and [background job](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.BackgroundJobs.HangFire)
- When we delete from hangfire dashboard it's still processing
```csharp
//Enqueue job
public async Task ExecuteAsync()
{
    await _backgroundJobManager.EnqueueAsync(new BackgroundTestJobArgs());
}

public class BackgroundTestJob : AsyncBackgroundJob<BackgroundTestJobArgs>, ITransientDependency
{
    public override async Task ExecuteAsync(BackgroundTestJobArgs args)
    {
            Logger.LogInformation("Job start: {Date}", DateTime.Now);
            
            await Task.Delay(TimeSpan.FromSeconds(5));
            Logger.LogInformation("Step1 done: {Date}", DateTime.Now);

            await Task.Delay(TimeSpan.FromSeconds(5));
            Logger.LogInformation("Step2 done: {Date}", DateTime.Now);

            Logger.LogInformation("Job end: {Date}", DateTime.Now);
    }
}

/* Output after cancellation
[17:17:03 INF] Job start: 01/01/2023 17:08:03
[17:17:08 INF] Step1 done: 01/01/2023 17:08:08
[17:17:13 INF] Step2 done: 01/01/2023 17:08:13
[17:17:13 INF] Job end: 01/01/2023 17:08:13
*/
```
image

### If we delete when it's processing it's must cancel background job

image

### Actual behavior

_No response_

### Regression?

_No response_

### Known Workarounds

_No response_

### Version

6.0.2, 7.0.0-rc.6

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ahmetfarukulu**
close #15281

⚠️  ~~Could  be **breaking change** for existing background jobs (We all need to add default [CancellationToken](https://github.com/ahmetfarukulu/abp/blob/dcd091adfbf94b3bcc6ad1ae9e7b75f47f22523d/framework/src/Volo.Abp.Emailing/Volo/Abp/Emailing/BackgroundEmailSendingJob.cs#L18) parameter)~~

### CODE REVIEW

**Comment by maliming** [comment]
hi

**Build failed for the solution: ../modules/background-jobs**

**Comment by ahmetfarukulu** [comment]
Hi, i forgot check background job module now fixed

**Comment by maliming** [comment]
hi @ahmetfarukulu 

Can you share some demo code to use this feature?

**Comment by ahmetfarukulu** [comment]
I added [hangfire](https://github.com/ahmetfarukulu/abp/blob/1c8ea86c3525dc061d3ddb8cae5f80e21256b5ba/modules/background-jobs/app/Volo.Abp.BackgroundJobs.DemoApp.HangFire/Program.cs#L21) and [quartz](https://github.com/ahmetfarukulu/abp/blob/1c8ea86c3525dc061d3ddb8cae5f80e21256b5ba/modules/background-jobs/app/Volo.Abp.BackgroundJobs.DemoApp.Quartz/Program.cs#L21) [long running job](https://github.com/ahmetfarukulu/abp/blob/1c8ea86c3525dc061d3ddb8cae5f80e21256b5ba/modules/background-jobs/app/Volo.Abp.BackgroundJobs.DemoApp.Shared/Jobs/LongRunningJob.cs) sample

image

**Review by maliming — APPROVED** [review]

**Comment by hikalkan** [comment]
Thank you @ahmetfarukulu for your contribution. However, this is an important breaking change that we can not accept.
I will suggest a way of doing this without breaking change.

1. Change `BackgroundJobExecuter` to call `ICancellationTokenProvider.Use` to set the cancellation token to ambient context:

image

here, you can get the actual token from somewhere (you already did it in this PR)

2. Then any background job can inject `ICancellationTokenProvider` and use its `Token` property. No need to do anything for that.

3. Document how to use cancellation token by adding a new "Cancelling Background Jobs" section under the Exception handling section of the document (https://docs.abp.io/en/abp/latest/Background-Jobs#exception-handling) (please include the documentation change in the PR)

**Review by hikalkan — CHANGES_REQUESTED** [review]
I requested changes here: https://github.com/abpframework/abp/pull/15282#issuecomment-1411704592

**Comment by ahmetfarukulu** [comment]
Thanks for the suggestion @hikalkan  this way more efficient

**Review by hikalkan — APPROVED** [review]

**Pull request merged**
