### PR TITLE
#1134 Create methods should care multitenancy.

### PR DESCRIPTION
**Pull request by mehmetuken**
#1134

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks a lot :)

**Comment by maliming** [comment]
hi @mehmetuken 
Should we check if the current entity's TenantId has a value and then assign it?

**Comment by hikalkan** [comment]
With current design, it is impossible that entity has a tenant id because we are calling TryToSetTenantId just after the MapToEntity. One exception can be if input has TenantId:

````csharp
var entity = MapToEntity(input);

if(entity is IMultiTenant)
{
    TryToSetTenantId(entity);
}
````

Actually `null` tenant id value is even a valid value (we may want to create a host entity with tenantid is null while working with a tenant user where currenttenant.id is not null - and in this case we are overriding it).

So, a good improvement can be like this:

````csharp
var entity = MapToEntity(input);
if(entity is IMultiTenant && !HasTenantIdProperty(input))
{
    TryToSetTenantId(entity);
}
````

This solves all problems. Can you implement this and send a PR please.

**Comment by maliming** [comment]
He may use the automapper to configure TenantId. Not necessarily in the input class.
Of course this may not be common.

**Comment by hikalkan** [comment]
Using automapper is not good since automapping configuration code can not access to Dependency Injection services. We can ignore it.

**Pull request merged**
