### PR TITLE
IdentityServer Module translations

### PR DESCRIPTION
**Pull request by afresh**

### CODE REVIEW

**Review by afresh — COMMENTED** [review]
Code review completed.

**Comment by berkansasmaz** [comment]
Thanks for your contribution ✌️

**Review by realLiangshiwei — APPROVED** [review]

**Comment by afresh** [comment]
@realLiangshiwei Hello, I have a question about this pr. I find that you have changed the Chinese punctuation into English punctuation. What is the reason for this?

**Comment by realLiangshiwei** [comment]
Hi @afresh , because we always use English punctuation in documents, in order to keep the style uniform, so I made changes,

**Comment by afresh** [comment]
@realLiangshiwei Thank you. I understand.

**Pull request merged**
