### PR TITLE
GetListByNormalizedRoleNameAsync does not return the expected result

### PR DESCRIPTION
**Pull request by muratyuceer**
GetListByNormalizedRoleNameAsync function does not return the expected result because the datafilters is not applied

### CODE REVIEW

**Comment by muratyuceer** [comment]
Does the same issue happen in entityframework repository? If not, why them not have same logic.

**Comment by hikalkan** [comment]
@muratyuceer EF data filtering relies on EF Core's global query filters, so we don't need a manual filtering.

**Comment by realLiangshiwei** [comment]
Hi @muratyuceer,

I don't think the method will return the unexpected result, it finally queries the user and will be filtered

**Comment by hikalkan** [comment]
I fixed this by https://github.com/abpframework/abp/pull/10614

Thanks @muratyuceer

**Pull request closed without merging**
