### PR TITLE
CLI: Run abp bundle on add-module for Blazor UI

### LINKED ISSUE #6468: CLI: Run abp bundle on add-module for Blazor UI
For Blazor UI projects, add-module and add-package commands should trigger `abp bundle` for the Blazor project. In this way, if new module needs to add a global script/style, it will be automatically added.

Send PR to me and @ilkayilknur

### PR DESCRIPTION
**Pull request by yekalkan**
resolves https://github.com/abpframework/abp/issues/6468

### CODE REVIEW

**Comment by ilkayilknur** [comment]
LGTM. Did you test the command? @yekalkan  You may need to pass the build argument to the bundle command since the bundle command uses the project output.

**Comment by yekalkan** [comment]
>You may need to pass the build argument to the bundle command since the bundle command uses the project output.

You mean `-f` (`--force`)?

**Comment by ilkayilknur** [comment]
> > You may need to pass the build argument to the bundle command since the bundle command uses the project output.
> 
> You mean `-f` (`--force`)?

Sorry yes. `-f` builds the project before discovering the contributers.

**Comment by yekalkan** [comment]
@ilkayilknur ok, i've added.

**Review by ilkayilknur — APPROVED** [review]

**Pull request merged**
