### PR TITLE
Create a FomrGroup instance #Angular documentation 

### PR DESCRIPTION
**Pull request by amsaighi**
The team had forgotten to instance the Form group.
Following the official docs [Grouping form controls](https://angular.io/guide/reactive-forms#grouping-form-controls)

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks @amSaighi for that fix.

**Comment by amsaighi** [comment]
> Thanks @amSaighi for that fix. 

U're welcome

**Comment by rqx110** [comment]
it has been created from buildForm function using "formbuilder",  should create again?

**Comment by armanozak** [comment]
Hi @amSaighi,

As @rqx110 expressed, the form group is created by the `buildForm` method [here](https://docs.abp.io/en/abp/latest/Tutorials/Part-3?UI=NG&DB=EF#create-a-reactive-form) using the `FormBuilder`. The `createBook` method is called when the `::NewBook` button is clicked. There is no need to create it on component initiation.

Thanks for your suggestion. I am closing this PR.

**Pull request closed without merging**
