### PR TITLE
Update PostgreSQL-Integration.md

### PR DESCRIPTION
**Pull request by xyfy**
add a description for add new Aggregate Roots / Entities

### CODE REVIEW

**Comment by maliming** [comment]
The contents of this pr are not unique to Postgresql.

**Comment by xyfy** [comment]
yes，but i do not&nbsp; found&nbsp; one&nbsp; for SQL server



---Original---

**Comment by xyfy** [comment]
Shoud  I  to remove it to [https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I](https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I)

**Comment by xyfy** [comment]
I move it #2114   and  will  close it here

**Pull request closed without merging**
