### PR TITLE
Add default logo definitions to templates

### PR DESCRIPTION
**Pull request by enisn**
### Description

Resolves https://github.com/abpframework/abp/issues/19780

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### CODE REVIEW

**Review by masum-ulu — APPROVED** [review]

**Review by oykuermann — CHANGES_REQUESTED** [review]
There is no logo on Blazor templates:
image

**Comment by enisn** [comment]
> There is no logo on Blazor templates: image

Which blazor templates?

---
Here what fixes this PR:
- app
  - Blazor.Server
  - Blazor.WebApp
- app-nolayers
   - Blazor.Mongo
   - Blazor.Server

**Comment by oykuermann** [comment]
Blazor server & Blazor wasm app templates
I didn't check no-layers

**Comment by enisn** [comment]
> Blazor server & Blazor wasm app templates I didn't check no-layers

I works on both WASM & server in this branch:

image

Can you try with hard refresh on browser?

**Review by oykuermann — APPROVED** [review]

**Pull request merged**
