### PR TITLE
ValidIssuers configuration option and code added to .HttpApi.Host and…

### PR DESCRIPTION
**Pull request by leonkosak**
… .Web projects

Valid IdentityServer issuers should be separated by comma char (,) if there is need for more valid IDS issuers.

### CODE REVIEW

**Comment by leonkosak** [comment]
@hikalkan, should this config property and code be added to .Blazor.Server and Blazor.Server.Tiered projects?

**Comment by maliming** [comment]
This does not work for the wildcard domain.  `https://{0}.abp.io`

https://github.com/abpframework/abp/issues/5589
https://gist.github.com/maliming/37193c20c2bea4c4779164d95b42d8f7#gistcomment-3638158

**Comment by leonkosak** [comment]
@maliming, so adding AbpIssuerValidator.cs and `options.TokenValidationParameters.IssuerValidator = AbpIssuerValidator.IssuerValidator;` should resolve this wildcard issue?

**Comment by maliming** [comment]
Yes, this is an option

**Comment by leonkosak** [comment]
@maliming, if `AbpIssuerValidator.cs` file is added to each individual project is appropriate solution or not?

**Comment by maliming** [comment]
We can publish a package that includes the AbpIssuerValidator. It just a sample.

**Comment by leonkosak** [comment]
Great! Please make a package and let me know the name.
Thank you.

**Comment by maliming** [comment]
ok

**Comment by leonkosak** [comment]
@maliming in which package is now AbpIssuerValidator.cs?

**Comment by maliming** [comment]
I will publish a package on NuGet this weekend.

**Comment by maliming** [comment]
https://github.com/maliming/Owl.TokenWildcardIssuerValidator

**Comment by MichelZ** [comment]
@maliming this package does not seem to be available anymore on GitHub. Is there a replacement? Or how is this achieved nowadays? Documentation is quite non-existent for this :(

**Comment by maliming** [comment]
hi @MichelZ It's available now.

**Pull request closed without merging**
