### PR TITLE
Resolve #1382 Use the new Redis package.

### LINKED ISSUE #1382: Use the new Redis package. Microsoft.Extensions.Caching.Redis => Microsoft.Extensions.Caching.StackExchangeRedis
see: https://github.com/aspnet/AspNetCore/issues/3606?tdsourcetag=s_pctim_aiomsg#issue-368901497

### PR DESCRIPTION
**Pull request by maliming**

### CODE REVIEW

**Comment by hikalkan** [comment]
Does this removes need to add ChangeAliasesOfStrongNameAssemblies lines to .csproj files? Example:

https://github.com/abpframework/abp/blob/fd60fa9c7e98fa55c14e8527138023ccbc9a0c08/samples/MicroserviceDemo/applications/AuthServer.Host/AuthServer.Host.csproj#L45-L51

Because, currently it doesn't compile unless we add this to csproj files. If that's not needed anymore, can you remove them?

**Comment by maliming** [comment]
I will confirm it.

**Comment by hikalkan** [comment]
Thanks a lot. Have you tested (at least a build & run)?

**Comment by maliming** [comment]
Yes.

The official introduction only needs to modify the method name and the other does not need to be changed.

I have successfully build and tested one of the projects, redis normal read and write.

**Comment by hikalkan** [comment]
Thanks a lot.

**Pull request merged**
