### PR TITLE
resolve #2385 fix mongo.exe dispose

### LINKED ISSUE #2385: The mongodb.exe process to continue running after the unit test is over.
https://github.com/abpframework/abp/issues/1632#issuecomment-563386192

image

### PR DESCRIPTION
**Pull request by mehmetuken**
using xunit collection fixtures

ref: https://xunit.net/docs/shared-context

### CODE REVIEW

**Comment by maliming** [comment]
This is great 👍 , I will test it as soon as possible.

**Comment by hikalkan** [comment]
Thanks @mehmetuken 

I also want to review this in the next milestone. First impression: I didn't like to add [Collection(MongoTestCollection.Name)] to every test class. If this is the only solution, we should be sure that this will not be a problem in the future.

**Comment by mehmetuken** [comment]
I was search this solution i found only way any tests share same context we collected all tests single collection. Because other way we don't now which test is finish or runing. The way collected tests and we share the same context. 

xunit document say:

>Collection Fixtures
 When to use: when you want to create a single test context and share it among tests in several test classes, and have it cleaned up after all the tests in the test classes have finished.

**Comment by hikalkan** [comment]
Thank you @mehmetuken I finally merged it. It is the only way to fix this issue.

**Pull request merged**
