### PR TITLE
removed pages prefix

### LINKED ISSUE #12803: CMS Kit - Remove `/pages` prefix from pages
When a page created, is has default `/pages/{page-slug}`.

Only `/{page-slug}` can be used as page url.

### PR DESCRIPTION
**Pull request by malikmasis**
closes https://github.com/abpframework/abp/issues/12803

### CODE REVIEW

**Comment by enisn** [comment]
image

We can update tooltips too

**Comment by enisn** [comment]
I can't find any issue for this.

@gizemmutukurt Can you check this too? There shouldn't be a problem with existing module URLs

**Review by enisn — APPROVED** [review]

**Review by gizemmutukurt — CHANGES_REQUESTED** [review]
The error in isuue will be fixed, it has been determined that it is not related to this issue

https://github.com/abpframework/abp/issues/13723

**Comment by enisn** [comment]
> I added a page named "source" and when I try to navigate to it I get an error.
> 
> image
> 
> image

I think content is null in that case. Markdown rendering can be disabled if the content is null.

**Review by gizemmutukurt — APPROVED** [review]

**Comment by enisn** [comment]
It doesn't break anything at the moment.

**Pull request merged**
