### PR TITLE
Fix the issue for the ProxyScript can not refresh, And some comments are wrong.

### PR DESCRIPTION
**Pull request by ilonze**
Fix the issue for the ProxyScript can not refresh.
When after I use the url with “useCache=false” parameter request proxy script WebApi, the cache is not refreshed when I use the url without “useCache” parameter  request proxy script WebApi.
And revise some wrong for some comments.

### CODE REVIEW

**Review by maliming — CHANGES_REQUESTED** [review]
hi

Can you provide steps that reproduce the problem.

**Comment by ilonze** [comment]
> hi
> 
> Can you provide steps that reproduce the problem.

steps:

1. request url "/abp/serviceproxyscript?type=jquery" and got the script first
2. request url "/abp/serviceproxyscript?type=jquery&useCache=false" and got the new script
3. request url "/abp/serviceproxyscript?type=jquery" again, but the script not same with step 2.

I find the issue in gateway, gateway aggregate api definition for some service host, when add a new service host, the script result is can not refreshed. I find this code in `ProxyScriptManager`:
```
private string CreateCacheKey(ProxyScriptingModel model)
{
    return _jsonSerializer.Serialize(model).ToMd5();
}
```
Md5 encrypt by all of the class ProxyScriptingModel's properties for key.
I think UseCache property not to Md5.

**Comment by maliming** [comment]
Thanks, I will check this, but I'll not use `[Newtonsoft.Json.JsonIgnore]` and `[System.Text.Json.Serialization.JsonIgnore]`

**Comment by ilonze** [comment]
> Thanks, I will check this, but I'll not use `[Newtonsoft.Json.JsonIgnore]` and `[System.Text.Json.Serialization.JsonIgnore]`

IJsonSerializer is not use Newtonsoft.Json or System.Text.Json?

**Comment by maliming** [comment]
You can do that:

```cs
private string CreateCacheKey(ProxyScriptingModel model)
{
	return _jsonSerializer.Serialize(new
	{
		model.GeneratorType,
		model.Modules,
		model.Controllers,
		model.Actions,
		model.Properties
	}).ToMd5();
}

```

**Comment by maliming** [comment]
Your commits contain irrelevant content.

image

**Comment by ilonze** [comment]
> Your commits contain irrelevant content.
> 
> image

These commits are all generated by merging them from the ABP code repository.
And revise some wrong for some comments.

**Comment by maliming** [comment]
no problem, I will open another pr.

**Comment by ilonze** [comment]
> no problem, I will open another pr.

Thanks!

**Pull request closed without merging**
