### PR TITLE
`EnableTracking` if the `entity` has `ObjectExtensionInfo`.

### PR DESCRIPTION
**Pull request by maliming**
The [FillExtraPropertiesForTrackedEntities](https://github.com/abpframework/abp/blob/961dfbae37d54013d97eb89a985238d9ab7e669f/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L284-L293) method of `AbpDbContext` required `Change Tracking.`

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks. Can we indicate that in the object extension documentation?

**Comment by maliming** [comment]
The document has been updated.

https://github.com/abpframework/abp/pull/19394/commits/a5de48116db156aa9d9ac601eea4ca4cb1c584b8

**Comment by hikalkan** [comment]
The document write that they should manually change the object tracking behavior. However, if I didn't misunderstand the code, it automatically enables it. Which one is true?

**Comment by maliming** [comment]
There are two parts:

1. **EntityCacheBase**:
If the entity has `extension properties`, we will `EnableTracking(IReadOnlyRepository)` in `EntityCacheBase`.

2. **Repository**:
If an entity has `extension properties(MapEfCoreProperty),` the developer can't use the read-only repository.

**Review by hikalkan — APPROVED** [review]

**Comment by hikalkan** [comment]
Thank you for the explanation. It is clear for me now.

**Pull request merged**
