### PR TITLE
Fix attributes on PermissionDefinitionContext

### PR DESCRIPTION
**Pull request by puschie286**
Correct the [NotNull] and [CanBeNull] attributes for IPermissionDefinitionContext and remove these attributes from the implementation

### CODE REVIEW

**Comment by EngincanV** [comment]
Hi @puschie286, thanks for your contribution. There are some indentation problems on your PR. Also, these attributes are required to make the `PermissionDefinitionContext` more reliable. So, I close the PR thanks again.

**Comment by puschie286** [comment]
@EngincanV some attributes are confused and i tried to stick to your guide line to have attributes in the interface not in the implementation

**Comment by puschie286** [comment]
i mean you put NotNull on GetGroupOrNull return. so either the name is wrong or the attribute is wrong
@EngincanV

**Comment by EngincanV** [comment]
Yes, some of the attributes should change. Please check [this PR](https://github.com/abpframework/abp/pull/11350). Thanks for your contribution again @puschie286

**Comment by puschie286** [comment]
Great, thanks :)
  
  
  
    
  

  
  
>

**Pull request closed without merging**
