### PR TITLE
Optimize hide abp end points

### PR DESCRIPTION
**Pull request by masoodkhoshgard**
Resolves #14187

When using option HideAbpEndpoints, it only deletes the endpoints and still displays the schemas. With this correction, this issue will be resolved.

### CODE REVIEW

**Review by EngincanV — CHANGES_REQUESTED** [review]
Hi, can you remove the changes that you made in [AbpSelectTagHelperService.cs](https://github.com/abpframework/abp/pull/17151/files#diff-3f1ec22cd32d1375da7c75dfd129c35425dd1627114a505a35549df4b4ca8fb3) and [AbpInputTagHelperService.cs](https://github.com/abpframework/abp/pull/17151/files#diff-6b1fd1fa5180d344ab16ebc38769226bb1bf6699ba23d3bcf3e296541516487e). Because, they are not subject to this PR, please create a new PR for them.

Also, I think we can directly remove schemas that start with the `Volo.` prefix (`ActionUrlPrefixes`), what do you think?

**Comment by masoodkhoshgard** [comment]
Hi @EngincanV 
Of course, I will remove the [AbpSelectTagHelperService.cs](https://github.com/abpframework/abp/pull/17151/files#diff-3f1ec22cd32d1375da7c75dfd129c35425dd1627114a505a35549df4b4ca8fb3) and [AbpInputTagHelperService.cs](https://github.com/abpframework/abp/pull/17151/files#diff-6b1fd1fa5180d344ab16ebc38769226bb1bf6699ba23d3bcf3e296541516487e).
I already added PR #17129 for this
If remove the schemas that start with the Volo. prefix (ActionUrlPrefixes), it will also **Volo.Abp.Http.RemoteServiceErrorInfo**,
**Volo.Abp.Http.RemoteServiceErrorResponse** and
**Volo.Abp.Http.RemoteServiceValidationErrorInfo**
 removes that causes an error

**Review by EngincanV — APPROVED** [review]

**Comment by EngincanV** [comment]
Thanks for your contribution @masoodkhoshgard 🎉

**Comment by maliming** [comment]
hi

This pr has a bug.

https://github.com/abpframework/abp/pull/17510

**Pull request merged**
