### PR TITLE
Update leptonx-lite version to 1.0.0-beta.3 for templates

### PR DESCRIPTION
**Pull request by EngincanV**
@gizemmutukurt can you test the templates with some UI options. (I've tested with MVC and it works fine. FYI.)

Also, you can test the https://github.com/abpframework/abp/pull/12938#issue-1264624279 or create a separate issue for that.

### CODE REVIEW

**Comment by gizemmutukurt** [comment]
- I am getting the following error for Blazor server and the left menu is empty even though I am logged in. (**app** template)

image

- I am getting the following error for Blazor WASM and the left menu is empty even though I am logged in. (**app** template)

image

- Angular project has marked corruption in user permissions (**app** template)

image

**Comment by ismcagdas** [comment]
@gizemmutukurt could you clear browser cache and try blazor templates again ? I tried Blazor Server template and didn't get the error you are getting.

**Comment by EngincanV** [comment]
> @gizemmutukurt could you clear browser cache and try blazor templates again ? I tried Blazor Server template and didn't get the error you are getting.

I've also faced the same problem as Gizem does. But when I refreshed the page, console errors were hidden and the menu is loaded. FYI @ismcagdas

**Comment by EngincanV** [comment]
## app template

### mvc 

I could not face with any problems.

### blazor-server

There is a problem in the Tenants page for blazor-server ui. (**app** template). And also -> https://github.com/abpframework/abp/pull/13094#issuecomment-1165236598

blazor-server-tenant-page

### blazor

Blazor WASM is not working due to the following console error.

image

### angular

I could not face with any problems. But, I have seen a missing localization in logged out page as below.

image

## app-nolayers template

### mvc

I could not face with any problems.

### blazor-server

I could not face with any problems.

### angular

I could not face with any problems. But, I have seen a missing localization on logged out page as below.

image

**Comment by gizemmutukurt** [comment]
> @gizemmutukurt could you clear browser cache and try blazor templates again ? I tried Blazor Server template and didn't get the error you are getting.

Even though I cleared the browser cache, the problem still persists in Blazor Wasm.

682ab73c-c77b-452d-8cb7-bc8906f87d44

**Comment by muhammedaltug** [comment]
Logout screens are MVC pages. Can you try with resource owner password flow to test angular's auth screens?

**Comment by naderjavid** [comment]
Hi, still rtl languages has issues
[issues list](https://github.com/abpframework/abp/issues/13087)

**Comment by EngincanV** [comment]
I close this PR, since there are some problems in v1.0.0-beta.3 for LeptonX-Lite Theme. When v1.0.0-beta.4 released, I'll update the related startup templates within a new PR.

**Pull request closed without merging**
