### PR TITLE
feat: french localization

### PR DESCRIPTION
**Pull request by badre429**

### CODE REVIEW

**Comment by maliming** [comment]
hi @badre429  

Could you create PR in **dev** branch?

**Comment by badre429** [comment]
@maliming  
hi if possible we need french  localization for 3.2 since localization is not  has no impact on behavior of rc

**Comment by hikalkan** [comment]
I agree about to merge this to rel-3.2. In fact, we should always complete the localizations in the preview period.
So, thank you @badre429 

@maliming it seems OK to me, can you merge, then test it?

**Review by hikalkan — APPROVED** [review]

**Comment by maliming** [comment]
I'll test it in next RC.

**Pull request merged**
