### PR TITLE
Add naming convensions rewriter

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by maliming** [comment]
Related: https://github.com/abpframework/abp/pull/6287

**Comment by ldias91** [comment]
Any prediction to merge this pull request?

I am using this framework, but due to requirements the names of tables and columns must be in Snake Case.

Thanks!

**Comment by maliming** [comment]
There are some questions: See https://github.com/abpframework/abp/pull/6287

**Comment by ldias91** [comment]
@maliming thanks for response.

I checked the issue #6287 and see yours comment https://github.com/abpframework/abp/pull/6287#issuecomment-731898298 when you say :
> By the way, there are some bugs in EFCore.NamingConventions. We have to wait for its official version.
> 
> https://github.com/efcore/EFCore.NamingConventions/issues?q=is%3Aissue+label%3Abug+milestone%3A5.0.0

I checked the repository https://github.com/efcore/EFCore.NamingConventions and version 5.0 has already been released.

Since it has already been released is it possible to proceed with this?

Thanks!

**Comment by maliming** [comment]
hi @ldias91 
There are some review need to resolve.

https://github.com/abpframework/abp/pull/6287#pullrequestreview-536149479

**Pull request closed without merging**
