### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This PR reduces memory allocations and cleans up memory after use (currently _localSyncObjects just keeps growing depending on the keys you give it and never cleans up, potentially leading to a memory leak).

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@maliming what happened to the tests? I tried merging the latest commit hoping it would restart.

**Comment by MarkCiliaVincenti** [comment]
@maliming please try again. Also I'm not sure if this is the expected behaviour in the current code but please note that currently if you do not pass on a timeout (leave it as default), no blocking takes place at all.

**Comment by MarkCiliaVincenti** [comment]
@maliming ready from changes sorry about that. As explained in my previous message please ensure that this is the behaviour you want.

**Comment by MarkCiliaVincenti** [comment]
@maliming @hikalkan  what is the next step please?

**Comment by maliming** [comment]
> @maliming @hikalkan what is the next step please?

hi

I will check this asap.

**Comment by maliming** [comment]
hi @MarkCiliaVincenti 

In fact, `LocalAbpDistributedLock` will always be replaced by `MedallionAbpDistributedLock`, which means we will not use it.

**Comment by MarkCiliaVincenti** [comment]
I'm confused. Is LocalAbpDistributedLock unused?

**Comment by MarkCiliaVincenti** [comment]
> hi @MarkCiliaVincenti
> 
> In fact, `LocalAbpDistributedLock` will always be replaced by `MedallionAbpDistributedLock`, which means we will not use it.

I'm confused @maliming. Is `LocalAbpDistributedLock` unused?

**Comment by maliming** [comment]
We will use [Redis provider](https://github.com/madelson/DistributedLock/blob/master/docs/DistributedLock.Redis.md)

https://github.com/abpframework/abp/blob/c5df521b6c23f4809fed445b35cc0f9b8a5b7184/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web.Host/MyProjectNameWebModule.cs#LL244

https://docs.abp.io/en/abp/latest/Distributed-Locking#the-volo-abp-distributedlocking-abstractions-package

**Comment by MarkCiliaVincenti** [comment]
> We will use [Redis provider](https://github.com/madelson/DistributedLock/blob/master/docs/DistributedLock.Redis.md)
> 
> https://github.com/abpframework/abp/blob/c5df521b6c23f4809fed445b35cc0f9b8a5b7184/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web.Host/MyProjectNameWebModule.cs#LL244
> 
> https://docs.abp.io/en/abp/latest/Distributed-Locking#the-volo-abp-distributedlocking-abstractions-package

I'm still a bit confused and not quite understanding: is `LocalAbpDistributedLock` ever used or not? If it's not used, then you may as well delete it. If it's used, what is the issue with this PR?

**Comment by MarkCiliaVincenti** [comment]
@maliming

**Review by maliming — APPROVED** [review]

**Comment by MarkCiliaVincenti** [comment]
@maliming should this be in 7.2-preview?

**Comment by maliming** [comment]
I added it to the 7.2-preview milestone

**Comment by hikalkan** [comment]
Thanks @MarkCiliaVincenti for your great library and contributions to ABP. I just saw that. Great 👍

**Pull request merged**
