### PR TITLE
Feature Management Modal improvements

### LINKED ISSUE #5327: Feature Management Modal improvements (MVC UI)
image

* Checkboxes should be on the left side of the feature name
* Child features should be only selectable when the parent was selected (recursively), just like the permissions.
* Numeric features should properly validate numbers (also in the server) and should show a numeric textbox.
* Test if validators are properly working and fix if not.

These are valid for the SaaS module too.

I am currently writing the Features document: https://github.com/abpframework/abp/blob/rel-3.1/docs/en/Features.md
You can read the document when I complete (tomorrow) and work on this issue then.

### PR DESCRIPTION
**Pull request by realLiangshiwei**
Resolve https://github.com/abpframework/abp/issues/5327

ng

```csharp
var group = context.AddGroup("MyGroup");

var reporting = group.AddFeature(
    "MyGroup.Reporting",
    displayName: new FixedLocalizableString("Reporting"),
    defaultValue: "false",
    valueType: new ToggleStringValueType());

var pdfReporting = reporting.CreateChild(
    "MyGroup.Reporting.PdfReporting",
    displayName: new FixedLocalizableString("Pdf Reporting"),
    defaultValue: "false",
    valueType: new ToggleStringValueType());


pdfReporting.CreateChild(
    "MyGroup.Reporting.PdfReporting.Quality",
    displayName: new FixedLocalizableString("PdfReporting Quality"),
    defaultValue: "",
    valueType: new SelectionStringValueType()
    {
        ItemSource = new StaticSelectionStringValueItemSource(
            new LocalizableSelectionStringValueItem
            {
                Value = "TestValue",
                DisplayText = new LocalizableStringInfo("TestResourceName", "TestName")
            }, new LocalizableSelectionStringValueItem
            {
                Value = "TestValue2",
                DisplayText = new LocalizableStringInfo("TestResourceName", "TestName")
            }),
        Validator = new AlwaysValidValueValidator()
    });

var pdf = reporting.CreateChild(
    "MyGroup.Reporting.ExcelReporting",
    displayName: new FixedLocalizableString("Excel Reporting"),
    defaultValue: "false",
    valueType: new ToggleStringValueType());

pdf.CreateChild(
    "MyGroup.Reporting.ExcelReporting.FileName",
    displayName: new FixedLocalizableString("Pdf FileName"),
    defaultValue: "",
    valueType: new FreeTextStringValueType(new StringValueValidator(1, 3)));

reporting.CreateChild(
    "MyGroup.Reporting.MaxPage",
    displayName: new FixedLocalizableString("Max page"),
    defaultValue: "1",
    valueType: new FreeTextStringValueType());

group.AddFeature("MyGroup.Count",
    displayName: new FixedLocalizableString("Export max count"),
    valueType: new FreeTextStringValueType(new NumericValueValidator(0, 20)),
    defaultValue: "10");
```

### CODE REVIEW

**Comment by hikalkan** [comment]
Looks good :)

**Comment by hikalkan** [comment]
Please resolve the conflict ;)

**Comment by realLiangshiwei** [comment]
@hikalkan  done

**Comment by hikalkan** [comment]
Thanks, great!

**Pull request merged**
