### PR TITLE
Framework - Consider hard deleted entities in MongoDbRepository

### PR DESCRIPTION
**Pull request by enisn**
## Summary
MongoDbRepository doesn't handle HardDeleted entities with default implementation while deleting many. So this PR implements seperated logic for hard & soft deleted entities. 

First seen in  #7453

### CODE REVIEW

**Comment by maliming** [comment]
hi @enisn 
Could you add some unit tests for `DeleteManyAsync`?

**Comment by enisn** [comment]
@maliming 
HardDelete test-case is added into **HardDelete_Tests**

**Comment by olicooper** [comment]
Will this be merged in to rel-4.2?

**Comment by enisn** [comment]
@olicooper 
Soonest possibility is `v4.3.0-rc` since It's not urgent critical bug fix

**Review by maliming — APPROVED** [review]

**Comment by maliming** [comment]
hi @olicooper  You can try to merge **dev** branch to yours.

**Comment by olicooper** [comment]
@maliming I merged `dev` to [the PR](https://github.com/abpframework/abp/pull/7453) branch, then changed the PR base branch to `dev`. Hopefully this is okay for you.

**Pull request merged**
