### PR TITLE
Add indentityUser create method extraProperties property and Fix Localization problem on My Profile modal

### PR DESCRIPTION
**Pull request by Nokecy**

### CODE REVIEW

**Comment by hikalkan** [comment]
Thank you for your contribution.
But please send the localization fix as a separated PR.

We don't like to expose ExtraProperties directly to the clients, because it may be a security risk. We may store sensitive data in the ExtraProperties and we only want some of them to available to clients.

**Comment by hikalkan** [comment]
So, I'm closing this now. But please send the localization fix as a separated PR.
Thank you for your time.

**Comment by Nokecy** [comment]
@hikalkan  Can I know how to use ExtraProperties?   thanks！

**Comment by hikalkan** [comment]
It's just a dictionary. Get an entity from database, set a new value to dictionary and save again. That's all.

**Pull request closed without merging**
