### PR TITLE
Human Friendly Enums in Swagger

### PR DESCRIPTION
**Pull request by masoodkhoshgard**
### Description

User Friendly Enum

### Checklis

- [x] I fully tested it as developer 

### How to Use it?

Usage

### CODE REVIEW

**Comment by realLiangshiwei** [comment]
Hi @masoodkhoshgard 
Thanks for your contribution, the CI failed, could you check it? thanks.

**Comment by masoodkhoshgard** [comment]
Hi @realLiangshiwei, yes sure

**Comment by masoodkhoshgard** [comment]
Hi @realLiangshiwei, please check again

**Review by maliming — APPROVED** [review]

**Comment by maliming** [comment]
Thanks @masoodkhoshgard 👍

**Pull request merged**
