### PR TITLE
Support markdown in CMS-Kit comments

### LINKED ISSUE #10789: Support markdown in CMS-Kit comments

### PR DESCRIPTION
**Pull request by yekalkan**
resolves https://github.com/abpframework/abp/issues/10789

@berkansasmaz Can you check if it looks fine on community.abp.io?

image

### CODE REVIEW

**Comment by berkansasmaz** [comment]
There is a security vulnerability.

For example: 

Kapture 2021-12-01 at 09 59 18

**Comment by berkansasmaz** [comment]
I could not find any problem visually on [community.abp.io](https://commercial.abp.io/).

Screen Shot 2021-12-01 at 09 52 43

**Comment by yekalkan** [comment]
> There is a security vulnerability.

Now it is prevented.

**Comment by berkansasmaz** [comment]
LGTM 😊

**Review by enisn — APPROVED** [review]

**Review by hikalkan — APPROVED** [review]

**Comment by hikalkan** [comment]
Thanks all.

**Pull request merged**
