### PR TITLE
Init Document Node Breadcrumb

### PR DESCRIPTION
**Pull request by realLiangshiwei**
### Description

Resolves https://github.com/volosoft/volo/issues/18465

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### CODE REVIEW

**Review by salihozkara — APPROVED** [review]

**Review by gizemmutukurt — CHANGES_REQUESTED** [review]
- [ ] scroll is displayed.

image

- [ ] Does not scroll when scroll is long

image

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem. you can try restore npm packages

image

**Comment by gizemmutukurt** [comment]
> I can't reproduce the problem. you can try restore npm packages
> 
> image

Which computer do you use? Mac or Windows?

**Comment by gizemmutukurt** [comment]
> > I can't reproduce the problem. you can try restore npm packages
> > image
> 
> Which computer do you use? Mac or Windows?

this problem is independent of this pr.

**Review by gizemmutukurt — APPROVED** [review]

**Pull request merged**
