### PR TITLE
Configure extensible Dtos

### PR DESCRIPTION
**Pull request by liangshiw**
Resolve https://github.com/abpframework/abp/issues/4412

### CODE REVIEW

**Comment by RayMMond** [comment]
How to add data annotations to Dto's extended props?

**Comment by liangshiw** [comment]
@RayMMond 
See https://docs.abp.io/en/abp/latest/Object-Extensions#validation

**Comment by RayMMond** [comment]
@liangshiw Thanks 😄

**Comment by liangshiw** [comment]
@hikalkan 
Configure all Dtos (Input & Output) of the pre-build module to be extensible, What do you think?

**Comment by hikalkan** [comment]
@liangshiw we are planning to implement the module extend system for open source modules too. But inheriting from `ExtensibleObject` is just a part of this work.
(see this internal issues: https://github.com/volosoft/volo/issues/2084 & https://github.com/volosoft/volo/issues/2232)
So, you can cancel this PR & issue, we will be working on it.

**Comment by liangshiw** [comment]
OK.

**Pull request closed without merging**
