### PR TITLE
Application shutdown

### LINKED ISSUE #265: Manage application shutdown (using IApplicationLifetime for aspnet core)
Shutdown method is not being called yet.

### PR DESCRIPTION
**Pull request by mehmetuken**
Resolve #265 and #2066

### CODE REVIEW

**Comment by hikalkan** [comment]
Thank you @mehmetuken 

@maliming can you review & test this (with a console & web app - use existing sample projects).

**Comment by maliming** [comment]
Ok, I will do it.

**Comment by maliming** [comment]
After code review and testing of console and web application I think the code can be merged.

**Comment by mehmetuken** [comment]
AutofacServiceProvider from https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacServiceProvider.cs .
And this change not releated console app. Console apps doesn't yet using generic host. Manually run shutdown metod.

**Comment by maliming** [comment]
hi @mehmetuken 

The code of **AutofacServiceProvider** should be the **master** branch.

https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/master/src/Autofac.Extensions.DependencyInjection/AutofacServiceProvider.cs

The **develop** branch has new changes.

https://github.com/autofac/Autofac.Extensions.DependencyInjection/commit/de3276fa0d50fe310283e1e36526488654285b4e

**Comment by mehmetuken** [comment]
@maliming Yes i am not using IAsyncDisposable because Autofac 5 not release yet. ILifetimeScope not support IAsyncDisposable yet. Autofac 5 release we can update this.

**Comment by hikalkan** [comment]
Thank you @mehmetuken & @maliming

**Pull request merged**
