### PR TITLE
Add `@abp/qrcode` library.

### PR DESCRIPTION
**Pull request by maliming**
We will use it in the next feature.

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-7.0#adding-qr-codes-to-the-2fa-configuration-page
https://github.com/davidshimjs/qrcodejs/

### CODE REVIEW

**Review by realLiangshiwei — APPROVED** [review]

**Comment by buntysaraswat** [comment]
For Commercial License:-
Hello Team, With this change, will TOTP come out of the box or developer still needs to implement in the project?

**Comment by realLiangshiwei** [comment]
@buntysaraswat 
It‘s out of the box

**Comment by buntysaraswat** [comment]
YAAAY, will it be from version 7.2 or can it be in 7.1

**Comment by maliming** [comment]
> YAAAY, will it be from version 7.2 or can it be in 7.1

7.3

**Pull request merged**
