### PR TITLE
Soft Delete & Common Test Done for MemoryDB

### PR DESCRIPTION
**Pull request by iyilm4z**
Fixes [this](https://github.com/abpframework/abp/issues/2833).

### CODE REVIEW

**Comment by iyilm4z** [comment]
Hi @maliming tests failed. However as i can see it's related to `Volo.Abp.AspNetCore.Mvc.Tests`, not to my changes. Am i right? If not, what i'm missing?

failed-ss

success-ss

**Comment by maliming** [comment]
It should be related to your code. You can try to synchronize the code from the **dev** branch(Merge **dev** branch to your branch. ).

image

**Comment by iyilm4z** [comment]
@maliming you were right, it was related to my changes. i've synced my feature branch with upstream/dev. I also found [this](https://github.com/abpframework/abp/blob/363fc9c865d7903f5318d2a49c1f911e1b4c954a/framework/src/Volo.Abp.MemoryDb/Volo/Abp/Domain/Repositories/MemoryDb/MemoryDbRepository.cs#L35) line causes tests failed but i donno why:/i it's just a dependency of **IAuditPropertySetter**. I also realized that failing tests written by you, that's why you may be tell me the relation.

image

**Comment by maliming** [comment]
hi @iyilm4z  

It was fixed. https://github.com/abpframework/abp/pull/4453/commits/2d2a5cbebf59223613d035c99a15b265026aa5cc

**Comment by iyilm4z** [comment]
@maliming thank you. you are so helpful.

**Comment by maliming** [comment]
@iyilm4z Thank you for your contribution.

**Pull request merged**
