### PR TITLE
Permission management modal html

### PR DESCRIPTION
**Pull request by halimekarayay**
resolves 
 https://github.com/volosoft/vs-internal/issues/5065,
 https://github.com/volosoft/vs-internal/issues/5049,
 
https://github.com/user-attachments/assets/3fee3880-8540-44bd-ae83-d025e29f3f40

### CODE REVIEW

**Comment by ebicoglu** [comment]
Make filtering both on permission group and permission names

**Comment by rqx110** [comment]
Putting the "Check All" button behind the search box is really ugly.

**Review by ebicoglu — APPROVED** [review]

**Comment by ebicoglu** [comment]
I'll merge after @enisn completes the filtering function

**Comment by enisn** [comment]
The last logic is searching on both sides but shows/hides only left tabs
filter-permission-last

**Pull request merged**
