### PR TITLE
Implemented missing DependencyAttribute business for AspNetCore

### LINKED ISSUE #10375: DependencyAttribute doesn't work for AspNetCoreMvc
I realized this when i was working on #10343. This may be root couse of it.

### PR DESCRIPTION
**Pull request by iyilm4z**
Fixes #10375

### CODE REVIEW

**Comment by maliming** [comment]
hi @iyilm4z 

Can you add the unit test?

**Comment by maliming** [comment]
hi @iyilm4z 

I made some changes. You can check it.

https://github.com/abpframework/abp/pull/10376/commits/2919be386e723fcdd6b6ba60fa60cba4271d4c5b

**Comment by iyilm4z** [comment]
@maliming I could realize just a small piece of the related issue but you saw the bigger picture. That's your difference:) It looks clean, thanks.

**Review by maliming — APPROVED** [review]

**Comment by iyilm4z** [comment]
@maliming please ignore the second review request. It happened by accident.

**Comment by maliming** [comment]
Thanks again @iyilm4z

**Pull request merged**
