### PR TITLE
Adding spanish language (es) translation

### LINKED ISSUE #6305: ABP framework es-ES translation
The abp-translation.abp.es-ES translation has been updated with missing parts and now is 100% completed.

[abp-translation.abp.es-ES.zip](https://github.com/abpframework/abp/files/5578208/abp-translation.abp.es-ES.zip)

If you have any other documents to translate, only let me know.

### PR DESCRIPTION
**Pull request by jmglezgz**
Resolve https://github.com/abpframework/abp/issues/6305 

 abp_io/AbpIoLocalization/AbpIoLocalization/Account/Localization/Resources/es.json
 abp_io/AbpIoLocalization/AbpIoLocalization/Admin/Localization/Resources/es.json
 abp_io/AbpIoLocalization/AbpIoLocalization/Base/Localization/Resources/es.json
 abp_io/AbpIoLocalization/AbpIoLocalization/Commercial/Localization/Resources/es.json
 abp_io/AbpIoLocalization/AbpIoLocalization/Community/Localization/Resources/es.json
 abp_io/AbpIoLocalization/AbpIoLocalization/Www/Localization/Resources/es.json

### CODE REVIEW

**Comment by realLiangshiwei** [comment]
Hi @jmglezgz ,

Can you resolve these conflicts?

**Comment by jmglezgz** [comment]
Hi @realLiangshiwei,

yes sure, could you give me guidance on that?

**Comment by jmglezgz** [comment]
> Hi @realLiangshiwei,
> 
> yes sure, could you give me guidance on that?

I resolve conflicts manually using this page. Thanks

**Comment by jmglezgz** [comment]
Thanks guys for your support

**Pull request merged**
