### PR TITLE
Implemented the getting environment from remote URL

### LINKED ISSUE #4386: Angular: Read settings from Json files
Please modify Angular modules to read settings from Json files instead of **environment.ts** to allow overwriting settings in CD process, for instance change API Url per deploying environment.
   We saw the implementation of **AppPreBootstrap** which load settings from Json in ASP.NET Zero and tried to implement the logic in AbpCommercial but could not make it work somehow.

### PR DESCRIPTION
**Pull request by mehmet-erim**
Resolves #4386

Remote environment configuration can be added to the environment like below:

```ts
import { Config } from '@abp/ng.core';

export const environment = {
  production: false,
  hmr: false,
  remoteEnv: {
    url: '/assets/appsettings.json',
    method: 'GET',
    headers: {}
  }
} as Config.Environment;

```

### CODE REVIEW

**Comment by olicooper** [comment]
My implementation ([see here](https://github.com/abpframework/abp/issues/4386#issuecomment-668626553)) allowed for partial replacement and appending of nested properties using a package called `deepmerge`. Is this something you'd be able to add in to make it more flexible and similar to .NET Core's `appsettings.json` replacement? 

I could have the default `environment.ts` like this:
```javascript
{
  recaptcha: { enabled: false, siteKey: 'AAAA' }
}
```

And my `/assets/appsettings.json` like this:
```javascript
{
  recaptcha: { enabled: true  },
  anotherSetting: "hi"
}
```

Which results in:
```javascript
{
  recaptcha: { enabled: true, siteKey: 'AAAA' },
  anotherSetting: "hi"
}
```

You don't have to use the `deepmerge` package, but if you do then I'm not sure how you'd want to handle array merging...
https://github.com/TehShrike/deepmerge#arraymerge

**Comment by mehmet-erim** [comment]
Hi @olicooper

Thanks for your suggestion. We'll consider this.

**Comment by olicooper** [comment]
Could you also consider the option to suppress the `RestError` and gracefully fall back to the default environment configuration if the remoteEnv is not available? Maybe a simple console debug/warning log rather than passing it to the error handler and showing to the end user?

**Comment by olicooper** [comment]
I have just tried this on a staging environment and found an issue on the Angular UI...

I'm not sure why but the request to `/.well-known/openid-configuration` is made before the remoteEnv is configured. so the request is made to the wrong API (https://api.app.example.com instead of https://api.staging.example.com).

`environment.prod.ts`:
```javascript
{
  oAuthConfig: {
    issuer: 'https://api.app.example.com',
    // etc...
  },
  apis: {
    default: {
      url: 'https://api.app.example.com',
    },
  }
}
```

`appsettings.json`:
```javascript
{
  "oAuthConfig": {
    "issuer": "https://api.staging.example.com",
    // etc...
  },
  "apis": {
    "default": {
      "url": "https://api.staging.example.com"
    }
  }
}
```

I am using `@abp/ng.core 3.1.0-preview20200813`

**Comment by mehmet-erim** [comment]
> Could you also consider the option to suppress the `RestError` and gracefully fall back to the default environment configuration if the remoteEnv is not available? Maybe a simple console debug/warning log rather than passing it to the error handler and showing to the end user?

We will create an injection token to be able to get catch error function from the `AppModule`. See the related issue: https://github.com/abpframework/abp/issues/4992

I will check it. Thanks for the information.

**Comment by olicooper** [comment]
Perfect, great work! Thank you 👍

**Comment by olicooper** [comment]
@mehmet-erim I think I have fixed the problem.. https://github.com/abpframework/abp/pull/5058

**Pull request merged**
