### PR TITLE
Support `Keyed Services` in `DependencyAttribute`

### PR DESCRIPTION
**Pull request by htve**

### CODE REVIEW

**Comment by maliming** [comment]
hi

> Test failed for the solution: ../framework

We have a related https://github.com/abpframework/abp/pull/18792#event-11520780135 

It has made some changes to the keyed services.

Please merge your branch from `the` dev branch after merging.

**Comment by htve** [comment]
Friendly Review: Is this a duplicate feature? No, it's not. Is this a PR that needs a different PR to work, and no, it's not either.

**Comment by htve** [comment]
OMG, it looks like ABP.IO doesn't need contributions from contributors, even though this is an enhancement, and at the same time is suppressing unfriendly comments, which is a very scary thing.  

真听话, 你做的真棒, 看你怎么收场.

**Comment by v2codes** [comment]
Recover something：
34a1c59e4dfa524f311809bf3bd3761

-------------------------------------------------
What do you think about this?

**Pull request closed without merging**
