### PR TITLE
Use inner join instead of sub query

### LINKED ISSUE #17651: IdentityUserRepository.FindByLoginAsync generates 6 db queries
### Description

1. abp new LoginQuery -dbms MySQL

2. Add dataSeed
```csharp
public class LoginQueryDataSeedContributor : IDataSeedContributor, ITransientDependency
{
    private readonly IdentityUserManager _identityUserManager;

    public LoginQueryDataSeedContributor(IdentityUserManager identityUserManager)
    {
        _identityUserManager = identityUserManager;
    }

    public async Task SeedAsync(DataSeedContext context)
    {
        var user = await _identityUserManager.FindByNameAsync("admin");
        await _identityUserManager.AddLoginAsync(user,
            new UserLoginInfo("testLoginProvider", "testProviderKey", "tesat"));
    }
} 
```
3. Add query api
```csharp
public class LoginQueryIssueAppService : LoginQueryAppService, ILoginQueryIssueAppService
{
    private readonly IIdentityUserRepository _identityUserRepository;

    public LoginQueryIssueAppService(IIdentityUserRepository identityUserRepository)
    {
        _identityUserRepository = identityUserRepository;
    }

    public async Task<IdentityUserDto> GetAsync()
    {
        var user = await _identityUserRepository.FindByLoginAsync("testLoginProvider", "testProviderKey");
        return this.ObjectMapper.Map<IdentityUser, IdentityUserDto>(user);
    }
}
```

4. log
```log
[23:01:12 INF] Route matched with {action = "Get", controller = "LoginQueryIssue", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Identity.IdentityUserDto] GetAsync() on controller LoginQuery.LoginQueryIssueAppService (LoginQuery.Application).
[23:01:14 INF] Executed DbCommand (61ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__ef_filter__p_1='?' (DbType = Boolean), @__ef_filter__p_3='?' (DbType = Boolean), @__loginProvider_0='?' (Size = 64), @__providerKey_1='?' (Size = 196)], CommandType='Text', CommandTimeout='30']
SELECT `a`.`Id`, `a`.`AccessFailedCount`, `a`.`ConcurrencyStamp`, `a`.`CreationTime`, `a`.`CreatorId`, `a`.`DeleterId`, `a`.`DeletionTime`, `a`.`Email`, `a`.`EmailConfirmed`, `a`.`EntityVersion`, `a`.`ExtraProperties`, `a`.`IsActive`, `a`.`IsDeleted`, `a`.`IsExternal`, `a`.`LastModificationTime`, `a`.`LastModifierId`, `a`.`LastPasswordChangeTime`, `a`.`LockoutEnabled`, `a`.`LockoutEnd`, `a`.`Name`, `a`.`NormalizedEmail`, `a`.`NormalizedUserName`, `a`.`PasswordHash`, `a`.`PhoneNumber`, `a`.`PhoneNumberConfirmed`, `a`.`SecurityStamp`, `a`.`ShouldChangePasswordOnNextLogin`, `a`.`Surname`, `a`.`TenantId`, `a`.`TwoFactorEnabled`, `a`.`UserName`
FROM `AbpUsers` AS `a`
WHERE ((@__ef_filter__p_0 OR NOT (`a`.`IsDeleted`)) AND (@__ef_filter__p_1 OR (`a`.`TenantId` IS NULL))) AND EXISTS (
    SELECT 1
    FROM `AbpUserLogins` AS `a0`
    WHERE ((@__ef_filter__p_3 OR (`a0`.`TenantId` IS NULL)) AND (`a`.`Id` = `a0`.`UserId`)) AND ((`a0`.`LoginProvider` = @__loginProvider_0) AND (`a0`.`ProviderKey` = @__providerKey_1)))
ORDER BY `a`.`Id`
LIMIT 1
[23:01:14 INF] Executed DbCommand (26ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__ef_filter__p_1='?' (DbType = Boolean), @__ef_filter__p_3='?' (DbType = Boolean), @__loginProvider_0='?' (Size = 64), @__providerKey_1='?' (Size = 196), @__ef_filter__p_5='?' (DbType = Boolean)], CommandType='Text', CommandTimeout='30']
SELECT `t0`.`UserId`, `t0`.`RoleId`, `t0`.`TenantId`, `t`.`Id`
FROM (
    SELECT `a`.`Id`
    FROM `AbpUsers` AS `a`
    WHERE ((@__ef_filter__p_0 OR NOT (`a`.`IsDeleted`)) AND (@__ef_filter__p_1 OR (`a`.`TenantId` IS NULL))) AND EXISTS (
        SELECT 1
        FROM `AbpUserLogins` AS `a0`
        WHERE ((@__ef_filter__p_3 OR (`a0`.`TenantId` IS NULL)) AND (`a`.`Id` = `a0`.`UserId`)) AND ((`a0`.`LoginProvider` = @__loginProvider_0) AND (`a0`.`ProviderKey` = @__providerKey_1)))
    ORDER BY `a`.`Id`
    LIMIT 1
) AS `t`
INNER JOIN (
    SELECT `a1`.`UserId`, `a1`.`RoleId`, `a1`.`TenantId`
    FROM `AbpUserRoles` AS `a1`
    WHERE @__ef_filter__p_5 OR (`a1`.`TenantId` IS NULL)
) AS `t0` ON `t`.`Id` = `t0`.`UserId`
ORDER BY `t`.`Id`
[23:01:14 INF] Executed DbCommand (25ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__ef_filter__p_1='?' (DbType = Boolean), @__ef_filter__p_3='?' (DbType = Boolean), @__loginProvider_0='?' (Size = 64), @__providerKey_1='?' (Size = 196)], CommandType='Text', CommandTimeout='30']
SELECT `t0`.`UserId`, `t0`.`LoginProvider`, `t0`.`ProviderDisplayName`, `t0`.`ProviderKey`, `t0`.`TenantId`, `t`.`Id`
FROM (
    SELECT `a`.`Id`
    FROM `AbpUsers` AS `a`
    WHERE ((@__ef_filter__p_0 OR NOT (`a`.`IsDeleted`)) AND (@__ef_filter__p_1 OR (`a`.`TenantId` IS NULL))) AND EXISTS (
        SELECT 1
        FROM `AbpUserLogins` AS `a0`
        WHERE ((@__ef_filter__p_3 OR (`a0`.`TenantId` IS NULL)) AND (`a`.`Id` = `a0`.`UserId`)) AND ((`a0`.`LoginProvider` = @__loginProvider_0) AND (`a0`.`ProviderKey` = @__providerKey_1)))
    ORDER BY `a`.`Id`
    LIMIT 1
) AS `t`
INNER JOIN (
    SELECT `a1`.`UserId`, `a1`.`LoginProvider`, `a1`.`ProviderDisplayName`, `a1`.`ProviderKey`, `a1`.`TenantId`
    FROM `AbpUserLogins` AS `a1`
    WHERE @__ef_filter__p_3 OR (`a1`.`TenantId` IS NULL)
) AS `t0` ON `t`.`Id` = `t0`.`UserId`
ORDER BY `t`.`Id`
[23:01:14 INF] Executed DbCommand (25ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__ef_filter__p_1='?' (DbType = Boolean), @__ef_filter__p_3='?' (DbType = Boolean), @__loginProvider_0='?' (Size = 64), @__providerKey_1='?' (Size = 196), @__ef_filter__p_7='?' (DbType = Boolean)], CommandType='Text', CommandTimeout='30']
SELECT `t0`.`Id`, `t0`.`ClaimType`, `t0`.`ClaimValue`, `t0`.`TenantId`, `t0`.`UserId`, `t`.`Id`
FROM (
    SELECT `a`.`Id`
    FROM `AbpUsers` AS `a`
    WHERE ((@__ef_filter__p_0 OR NOT (`a`.`IsDeleted`)) AND (@__ef_filter__p_1 OR (`a`.`TenantId` IS NULL))) AND EXISTS (
        SELECT 1
        FROM `AbpUserLogins` AS `a0`
        WHERE ((@__ef_filter__p_3 OR (`a0`.`TenantId` IS NULL)) AND (`a`.`Id` = `a0`.`UserId`)) AND ((`a0`.`LoginProvider` = @__loginProvider_0) AND (`a0`.`ProviderKey` = @__providerKey_1)))
    ORDER BY `a`.`Id`
    LIMIT 1
) AS `t`
INNER JOIN (
    SELECT `a1`.`Id`, `a1`.`ClaimType`, `a1`.`ClaimValue`, `a1`.`TenantId`, `a1`.`UserId`
    FROM `AbpUserClaims` AS `a1`
    WHERE @__ef_filter__p_7 OR (`a1`.`TenantId` IS NULL)
) AS `t0` ON `t`.`Id` = `t0`.`UserId`
ORDER BY `t`.`Id`
[23:01:14 INF] Executed DbCommand (24ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__ef_filter__p_1='?' (DbType = Boolean), @__ef_filter__p_3='?' (DbType = Boolean), @__loginProvider_0='?' (Size = 64), @__providerKey_1='?' (Size = 196), @__ef_filter__p_9='?' (DbType = Boolean)], CommandType='Text', CommandTimeout='30']
SELECT `t0`.`UserId`, `t0`.`LoginProvider`, `t0`.`Name`, `t0`.`TenantId`, `t0`.`Value`, `t`.`Id`
FROM (
    SELECT `a`.`Id`
    FROM `AbpUsers` AS `a`
    WHERE ((@__ef_filter__p_0 OR NOT (`a`.`IsDeleted`)) AND (@__ef_filter__p_1 OR (`a`.`TenantId` IS NULL))) AND EXISTS (
        SELECT 1
        FROM `AbpUserLogins` AS `a0`
        WHERE ((@__ef_filter__p_3 OR (`a0`.`TenantId` IS NULL)) AND (`a`.`Id` = `a0`.`UserId`)) AND ((`a0`.`LoginProvider` = @__loginProvider_0) AND (`a0`.`ProviderKey` = @__providerKey_1)))
    ORDER BY `a`.`Id`
    LIMIT 1
) AS `t`
INNER JOIN (
    SELECT `a1`.`UserId`, `a1`.`LoginProvider`, `a1`.`Name`, `a1`.`TenantId`, `a1`.`Value`
    FROM `AbpUserTokens` AS `a1`
    WHERE @__ef_filter__p_9 OR (`a1`.`TenantId` IS NULL)
) AS `t0` ON `t`.`Id` = `t0`.`UserId`
ORDER BY `t`.`Id`
[23:01:14 INF] Executed DbCommand (25ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__ef_filter__p_1='?' (DbType = Boolean), @__ef_filter__p_3='?' (DbType = Boolean), @__loginProvider_0='?' (Size = 64), @__providerKey_1='?' (Size = 196), @__ef_filter__p_11='?' (DbType = Boolean)], CommandType='Text', CommandTimeout='30']
SELECT `t0`.`OrganizationUnitId`, `t0`.`UserId`, `t0`.`CreationTime`, `t0`.`CreatorId`, `t0`.`TenantId`, `t`.`Id`
FROM (
    SELECT `a`.`Id`
    FROM `AbpUsers` AS `a`
    WHERE ((@__ef_filter__p_0 OR NOT (`a`.`IsDeleted`)) AND (@__ef_filter__p_1 OR (`a`.`TenantId` IS NULL))) AND EXISTS (
        SELECT 1
        FROM `AbpUserLogins` AS `a0`
        WHERE ((@__ef_filter__p_3 OR (`a0`.`TenantId` IS NULL)) AND (`a`.`Id` = `a0`.`UserId`)) AND ((`a0`.`LoginProvider` = @__loginProvider_0) AND (`a0`.`ProviderKey` = @__providerKey_1)))
    ORDER BY `a`.`Id`
    LIMIT 1
) AS `t`
INNER JOIN (
    SELECT `a1`.`OrganizationUnitId`, `a1`.`UserId`, `a1`.`CreationTime`, `a1`.`CreatorId`, `a1`.`TenantId`
    FROM `AbpUserOrganizationUnits` AS `a1`
    WHERE @__ef_filter__p_11 OR (`a1`.`TenantId` IS NULL)
) AS `t0` ON `t`.`Id` = `t0`.`UserId`
ORDER BY `t`.`Id`

```

### PR DESCRIPTION
**Pull request by iswing**
Resolves #17651

### CODE REVIEW

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/issues/17651#issuecomment-1722213227

**Comment by hikalkan** [comment]
@iswing can you please sign that: https://github.com/abpframework/abp/pull/17655#issuecomment-1722461694

**Comment by maliming** [comment]
This is no problem when I set the `includeDetails` to `false`.

image

You will see some queries when `includeDetails` is `true` and this is by design.

https://github.com/abpframework/abp/issues/17651#issuecomment-1722213227

**Comment by iswing** [comment]
I think this pr solves another problem of slow query. In my case, there are about 40k records in abpusers table . Even if includedeails false is set, a single query still takes 1200ms. After I used inner join instead of sub query, the query takes only 2ms.

**Comment by maliming** [comment]
We have many queries way as same like the `FindByLoginAsync` method. 
Are you interested in changing all of them?

**Pull request closed without merging**
