### PR TITLE
Fix permission modal parent-child relations

### PR DESCRIPTION
**Pull request by mahmut-gundogdu**
Resolves [#12751](https://github.com/volosoft/volo/issues/12751)

### CODE REVIEW

**Comment by phil-enfom** [comment]
Hi @mahmut-gundogdu 
This change has fixed this issue as I have just confirmed on the dev app.
Can you ensure this fix gets pulled through to 7 on the next rc.

Thanks

Phil

**Review by muhammedaltug — APPROVED** [review]

**Comment by nev-21** [comment]
@muhammedaltug Will this work in version 7.0 final?

**Comment by mahmut-gundogdu** [comment]
> ill this work in version


Yes, this will released in version 7.0 final. In addition, 7.0 RC3 will be released (with this pr).   (A new RC will be made available today)

**Comment by nev-21** [comment]
Thanks @mahmut-gundogdu

**Pull request merged**
