### PR TITLE
Use Fody ConfigureAwait library instead of manual ConfigureAwait calls.

### PR DESCRIPTION
**Pull request by maliming**
```
<Import Project="configureawait.props" />

<Project>
  <ItemGroup>
      <PackageReference Include="ConfigureAwait.Fody" Version="3.3.1" />
      <PackageReference Include="Fody" Version="6.0.6">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>
  </ItemGroup>
</Project>
```
```
FodyWeavers.xml 

<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <ConfigureAwait ContinueOnCapturedContext="false" />
</Weavers> 
```

```
FodyWeavers.xsd 

<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- This file was generated by Fody. Manual changes to this file will be lost when your project is rebuilt. -->
  <xs:element name="Weavers">
    <xs:complexType>
      <xs:all>
        <xs:element name="ConfigureAwait" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="ContinueOnCapturedContext" type="xs:boolean" />
          </xs:complexType>
        </xs:element>
      </xs:all>
      <xs:attribute name="VerifyAssembly" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>'true' to run assembly verification (PEVerify) on the target assembly after all weavers have been executed.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="VerifyIgnoreCodes" type="xs:string">
        <xs:annotation>
          <xs:documentation>A comma-separated list of error codes that can be safely ignored in assembly verification.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="GenerateXsd" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>'false' to turn off automatic generation of the XML Schema file.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema> 
```

image

### CODE REVIEW

**Comment by maliming** [comment]
I will do more tests.

**Comment by hikalkan** [comment]
Related to https://github.com/abpframework/abp/issues/2577

**Comment by hikalkan** [comment]
@maliming if that's OK, I will merge.

**Comment by maliming** [comment]
I need to remove `ConfigureAwait(false)` in the test project.

**Comment by maliming** [comment]
If there are no other issues to investigate, you can merge it.

**Comment by hikalkan** [comment]
@maliming I forked your PR branch, compiled the code, opened the Volo.Abp.Authorization.dll (as an example) in the JetBrains DotPeek and didn't see the ConfigureAwait calls.

Screenshot:

image

What I am missing?

**Comment by maliming** [comment]
hi @hikalkan 
I use **ILSpy** and **dnSpy**.

image

**Pull request merged**
