### PR TITLE
Update Authorization.md

### PR DESCRIPTION
**Pull request by sturlath**
After back and fourth between me and @realLiangshiwei for few days I got the help to solve my problem https://github.com/abpframework/abp/discussions/9428 so here is giving some back.

I can add more code if you want or place this somewhere.. just let me know...

### CODE REVIEW

**Comment by realLiangshiwei** [comment]
Thanks, but I don't think this is a necessary change.

Because you using separate architecture, try using distributed events may be a better way.

**Comment by sturlath** [comment]
Basically just swap `ILocalEventHandler` for `IDistributedEventHandler` in the `EntityCreatedEventDataHandler`
Just like this? No need to use [Eto´s](https://docs.abp.io/en/abp/4.2/Distributed-Event-Bus) (I didn't find any that matched Identity like there is one for `TenantCreatedEto`)?

This code below worked at least locally.

```csharp
public class NewUserCreatedHandler : IDistributedEventHandler<EntityCreatedEventData<IdentityUser>>, ITransientDependency
{
...
}
```

So @realLiangshiwei, you don´t want to have this document update anywhere else?

**Comment by realLiangshiwei** [comment]
You can use Rabbitmq or other provider.

**Comment by sturlath** [comment]
So you are telling me that its not possible with `IDistributedEventHandler` (even though I got it to work). 

Why?

Will it only work locally or?

**Pull request closed without merging**
