### PR TITLE
Add multi tenant migrations to the migrator console application

### LINKED ISSUE #1371: Add multi tenant migrations to the migrator console application
In the `aspnetboilerplate` framework running the `Migrator` app would migrate the host database and all tenant databases that had a separate connection string.

Currently the migrator tool only migrates the host database and ignores tenants with own databases and connection strings.

Also the connection string is currently not stored encrypted.

### PR DESCRIPTION
**Pull request by gterdem**
Resolves #1371.

### CODE REVIEW

**Comment by leonkosak** [comment]
@hikalkan is somehow possible to have one migrator application and arguments for seed-ing host and tenant databases?

**Comment by hikalkan** [comment]
Yes, possible. Currently, it migrates all, you can easily make it parametric. The source code is in your solution.

**Comment by leonkosak** [comment]
@hikalkan This solution is great, but the better solution would be that IMyProjectNameDbSchemaMigrator would be "split":

- IMyProjectNameHostDbSchemaMigrator
- IMyProjectNameTenantSchemaMigrator

Of course, this also means two different OnModelCreating methods, but this should not be the "deal-breaker" if SQL tables for specific modules should be in host and tenant databases.
For such situation, the developer should be aware that ConfigureModuleName() method should be defined in OnModelCreating method for host and for tenant.

What do you think about this solution?

**Comment by hikalkan** [comment]
see https://github.com/abpframework/abp/issues/2993

**Comment by leonkosak** [comment]
I started, but then I realized that in my case, this is not useful enough to finalize development.

**Pull request merged**
