### PR TITLE
Introduce AbpClaimsPrincipalFactory.

### PR DESCRIPTION
**Pull request by realLiangshiwei**
Allow custom `IAbpClaimsPrincipalContributor` implementation to add custom claims.

Example:
```csharp
public class MyClaimsPrincipalContributor: IAbpClaimsPrincipalContributor, ITransientDependency
{
    public async Task ContributeAsync(AbpClaimsPrincipalContributorContext context)
    {
        var currentTenant = context.ServiceProvider.GetRequiredService<ICurrentTenant>();
        if (currentTenant.Id != null)
        {
            var tenantStore = context.ServiceProvider.GetRequiredService<ITenantStore>();
            var tenant = await tenantStore.FindAsync(tenantId.Value);
            var claimsIdentity = new ClaimsIdentity();
            claimsIdentity.AddIfNotContains(new Claim("tenantname", tenant.Name));
            context.ClaimsPrincipal.AddIdentity(claimsIdentity);
        }
    }
}
```

### CODE REVIEW

**Comment by hikalkan** [comment]
I also want to understand this, please don't merge.

**Comment by maliming** [comment]
Even if the developer does not use the identity module, he can still use **AbpClaimsPrincipalFactory**  to create **ClaimsPrincipal**.


https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.iauthenticationservice.signinasync?view=aspnetcore-5.0

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationhttpcontextextensions.signinasync?view=aspnetcore-5.0#Microsoft_AspNetCore_Authentication_AuthenticationHttpContextExtensions_SignInAsync_Microsoft_AspNetCore_Http_HttpContext_System_Security_Claims_ClaimsPrincipal_Microsoft_AspNetCore_Authentication_AuthenticationProperties_

**Review by maliming — APPROVED** [review]

**Comment by brunobertechini** [comment]
When using the IdentityModule, is this a recommended approach? Or which approach should be used (recommended one) to add a custom claim (lets say a value from database)

**Comment by maliming** [comment]
This PR allows other modules to provide claims. For example, the multi-tenant module can add the **Edition** of the tenant to the user's claims.

**Pull request merged**
