### PR TITLE
Make properties virtual on TenantCreateDto

### PR DESCRIPTION
**Pull request by olicooper**

### CODE REVIEW

**Comment by maliming** [comment]
hi
Can you share what is the use case? :)

**Comment by olicooper** [comment]
I would like to override the attributes on the password and email properties to make them not required, so I can provide a default value in the `IConfiguration`. Because the create tenant method doesn't use interfaces, I need to supply an instance of `TenantCreateDto` and this was the way I could think of that wouldn't be a breaking change.

**Comment by maliming** [comment]
> Because the create tenant method doesn't use interfaces

Can you point it out? Thanks.

**Comment by olicooper** [comment]
> > Because the create tenant method doesn't use interfaces
> 
> Can you point it out? Thanks.

Yeah sure, what I meant was that the `TenantAppService` CreateAsync method accepts a concrete class `TenantCreateDto` rather than an `ITenantCreateDto`interface  so I can't just override the method and supply my own class that inherits from this...
https://github.com/abpframework/abp/blob/1f2418b8721e0d991f2289bc4c57ca666de14c60/modules/tenant-management/src/Volo.Abp.TenantManagement.Application/Volo/Abp/TenantManagement/TenantAppService.cs#L45-L48

I think I prefer using virtual properties instead anyway. Or is there another way to specify that the `AdminEmailAddress` and `AdminPassword` properties not required that I might have missed?

**Pull request merged**
