### PR TITLE
dynamic form added nullable boolean render

### PR DESCRIPTION
**Pull request by blackWins**
```
public bool NotNullBoolean { get; set; }
public bool? NullableBoolean { get; set; }
```

image

### CODE REVIEW

**Comment by maliming** [comment]
hi

I think the `Indeterminate` is more suitable.

https://getbootstrap.com/docs/5.0/forms/checks-radios/#indeterminate

image

**Comment by blackWins** [comment]
sometime we use dynamic form render filter area, we want boolean type can set null 
image
like this ( `null` , `true` , `false` )
image

**Comment by maliming** [comment]
We can add an option to determine the result(select or checkbox)

**Comment by blackWins** [comment]
Use option to determine the result(select or checkbox) is not necessary

When use nullable `Boolean` there are three states ( `true`,`false` ,`null`) , using select should be more intuitive and convenient.

If the user only wants `true` or `false` , the checkbox is the best choice

**Comment by blackWins** [comment]
code like this , use `[BooleanSelector]` Attribute
```
        public bool BooleanDefault { get; set; }

        [BooleanSelector(emptyText:"Null",falseText:"False",trueText:"True")]
        public bool? NullableBoolean { get; set; }

        [BooleanSelector]
        public bool NotNullBoolean { get; set; }
```
UI like this
image

**Pull request closed without merging**
