### PR TITLE
#94 resolved

### PR DESCRIPTION
**Pull request by sercantimocin**
I have to use reflection instead of generic because I couldn't  find a way to get strongly type of custom mapper object from DI

### CODE REVIEW

**Comment by maliming** [comment]
hi @sercantimocin  Github action failed. https://github.com/abpframework/abp/pull/4498/checks

**Comment by hikalkan** [comment]
@maliming I am not sure this fail is related to this PR. Can you check and try to understand please?

**Comment by maliming** [comment]
@sercantimocin 
We have to handle or ignore calls in this way.
```cs
 ObjectMapper.Map<List<Entity>, EntityDto[]>(entitys)
```

**Comment by hikalkan** [comment]
I am closing this. You re-implement it when you start to work with the core ABP Framework team :)

**Pull request closed without merging**
