### PR TITLE
Converts project to use NuGet Central Package Management (CPM)

### LINKED ISSUE #16559: Using central package management
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management

> Starting with [NuGet 6.2](https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.2), you can centrally manage your dependencies in your projects with the addition of a Directory.Packages.props file and an MSBuild property.

### Describe the solution you'd like

abp currently uses `Directory.Build.props` to manage most nuget packages. 

I think we can improve the package management experience by using centralized package management. This also applies to templates, where developers can more easily check and manage all abp package versions.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by htve**
Resolves #16559

### CODE REVIEW

**Comment by maliming** [comment]
There are no `Directory.Packages.props`, `configureawait.props` files after the template project created by CLI.

**Comment by htve** [comment]
this pr has been modified and tested in build. I'm not familiar with the principles of other tools such as cli, so I didn't test it.

**Comment by maliming** [comment]
hi

We must create the `Directory.Packages.props` file for every template project.

The template project is independent.

**Comment by htve** [comment]
Yes, this is a huge project, I only completed 50% of it.  
I will submit a new PR today to solve the `Directory.Packages.props` file of the template project

- [x] Using standalone CPM files in template projects.

**Comment by maliming** [comment]
This is not urgen. Thank you for your contribution. Take your time.

**Comment by htve** [comment]
The template project has been added to the `Directory.Packages.props` file and a new PR has been submitted.

**Comment by htve** [comment]
Fixed a missing package reference error

**Comment by htve** [comment]
Fixed a missing package reference error and it successfully executed `build\build-all.ps1`

**Comment by htve** [comment]
The following is the remaining work. Due to too much text, I am temporarily writing in my native language.

剩余工作:
framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectBuilding/Building/Steps/ProjectReferenceReplaceStep.cs:  
>   NugetReferenceReplacer.GetNewReferenceNode:  
1.     从当前`.csproj`文件所在目录中或上级目录(一直向上,直到根目录)中搜索`Directory.Packages.props`文件;
    1.   如果已存在则返回完整文件路径;
    2.   如果不存在:   
        1.  从当前`.csproj`文件所在目录中或上级目录(一直向上,直到根目录)中搜索`.sln`文件, 如果存在则在`.sln`文件所在目录中创建默认`Directory.Packages.props`文件;
        2. 上一条为假时, 在当前`.csproj`文件所在目录中创建默认`Directory.Packages.props`文件;
        3. 返回完整文件路径.
2.     判断`Directory.Packages.props`中是否存在`nugetPackage`, 存在则替换`Version`为`_nugetPackageVersion`; 不存在则新增.

**Comment by htve** [comment]
@maliming The abp.cli  has been completed and the compatibility of app-7.3.3 has been successfully tested.

**Pull request closed without merging**
