### PR TITLE
Fix !important on vc.scss to solve issue on client side

### PR DESCRIPTION
**Pull request by andmattia**
### Description

Resolves a UI issue on doc module directly imported on a APB project.

### CODE REVIEW

**Comment by andmattia** [comment]
How can you solve this issue without !important tag on CSS?

**Comment by berkansasmaz** [comment]
Before we can properly review PR, we need to better understand what it solves. Is there an open issue related to the problem?

**Comment by andmattia** [comment]
No. 

It's quite simple to reproduce in 7.0.2.
1. Create empty project
2. Add Docs Module
3. Run

If you look in the right corner where project version is show you can see this issue
image

this is the css 
image

If you put !important in padding and backgroud props this gone away

image
image

I think this is caused by LeptonXPro in ```select2.scss``` 
```scss
input-group {
  .input-group-text {
    padding: 0.4rem 0.9rem !important;
    font-size: 0.875rem;
    color: var(--lpx-content-text) !important;
    background-color:  var(--lpx-card-bg)  !important; 
    border-radius: 0.475rem;
  }
...
```
I check your docs site but it use base and not LeptonXPro

**Comment by berkansasmaz** [comment]
Thank you for explaining the issue 🙏 Your PR will be reviewed as soon as possible 🥳

**Review by halimekarayay — APPROVED** [review]

**Review by berkansasmaz — APPROVED** [review]

**Review by armgnunlu — APPROVED** [review]

**Comment by berkansasmaz** [comment]
Hi @andmattia, we could not merge the PR due to conflict. We can't sync with dev because we don't have update permission. Can you update your branch?

**Comment by ebicoglu** [comment]
@andmattia fix the conflict please

**Comment by andmattia** [comment]
@berkansasmaz @ebicoglu  I've update my branch

**Review by berkansasmaz — APPROVED** [review]

**Comment by berkansasmaz** [comment]
@andmattia Unfortunately, the problem seems unresolved. We still can't merge PR. It seems that the problem is not with you, but as a result we are not able to merge the PR. Please fix the problem or create a new PR.

**Comment by berkansasmaz** [comment]
Hi @andmattia, sorry I had to [recreate](https://github.com/abpframework/abp/pull/16286) the PR. That's why I'm closing this PR.

Thank you so much for contributing 🥳🥳.

**Pull request closed without merging**
