### PR TITLE
Added a Modal Service to Project the Modal to Root Level

### LINKED ISSUE #3197: Create a modal service to append a modal to the body

### PR DESCRIPTION
**Pull request by armanozak**
Fixes #3197

### CODE REVIEW

**Comment by begandroide** [comment]
Hi! @armanozak is this availaible in release of abp? because i want to use the modal service from a custom component error wrapper and i cant import it. Here i leave a screenshot showing the actual error: 
image

Thank you in advance.

**Comment by mehmet-erim** [comment]
Hello @begandroide. 

It will be available as of v2.6. You can use the modal service until the new version is released by installing the preview NPM packages.

Run the following command In angular folder:

```bash
abp switch-to-preview
```

Replace the `.npmrc` file content with the below:

```
@abp:registry=https://www.myget.org/F/abp-nightly/npm
```

Then run the `yarn` command to install the preview packages.

**Comment by begandroide** [comment]
Hi @mehmet-erim, thanks a lot! 

One last question about the ThemeSharedModule in user interface: 

Im writting a custom error http wrapper component, the custom component is rendered on body with the tag or component name. The problem is that the `abp-http-error-wrapper` still appearing in body:

image

We can"disable" auto abp http wrapper component? because is duplicated data in dom,

thanks again.

**Comment by mehmet-erim** [comment]
@begandroide 

You can pass your custom error component to `forRoot` of `ThemeShared` like below:

```ts
    ThemeSharedModule.forRoot({
      httpErrorConfig: {
        errorScreen: {
          component: YourCustomHttpErrorComponent,
          forWhichErrors: [401, 403, 404, 500],
          hideCloseIcon: true,
        },
      },
    }),
```

Unfortunately, It can't be disabled. We can add a boolean named `skipErrorHandling` to skip errors by ErrorHandler. Please follow #3636

**Comment by begandroide** [comment]
@mehmet-erim 

I understood that can't be disabled, I was trying to remove ThemeSharedModule (abp) from my app module component, and in all the modules where was; keeping core module (abp). 

I thought that removing from modules the http wrapper error would not show, but persist in the body of dom. 

So, exist interdependece between abp/ng.core and abp/ng.theme.shared? I was thinking that RestService could be the "guilty".

Thanks for all your aswers 😄

**Comment by mehmet-erim** [comment]
@begandroide 
`error.handler.ts` file in the @abp/ng.theme.shared package appends `HttpErrorWrapperComponent` to the DOM. You can skip error handling in v2.6

**Pull request merged**
