### PR TITLE
Add missing localizations for admin side

### PR DESCRIPTION
**Pull request by berkansasmaz**

### CODE REVIEW

**Comment by DonVliet** [comment]
The english is not quite right in a few of the translations...

**"HowMayWeHelpYou": "How may we help you"**

should be

**"HowMayWeHelpYou": "How may we help you?"**

**"WeWillReplyYou": "Your message is sent! We will reply you in a short time."**

should be

**"WeWillReplyYou": "Your message has been sent! We will reply to you shortly."**

**"RegisterToTheNewsletter": "Register to the newsletter to get information on happenings about ABP.IO, like new releases."**

should be

**"RegisterToTheNewsletter": "Register for the newsletter to receive information regarding ABP.IO, including new releases etc."**

**"PaymentRequestsOf{0}Organization": "Payment request of \"{0}\" organization"**

should be

**"PaymentRequestsOf{0}Organization": "Payment request for \"{0}\" organization"**

**Comment by berkansasmaz** [comment]
Thank you very much for your comment @DonVliet. :pray: :pray:

**Comment by DonVliet** [comment]
Sorry :-( but you haven't made the correct change in the following:

**"PaymentRequestsOf{0}Organization": "Payment requests of \"{0}\" organization"**

should be 

**"PaymentRequestsOf{0}Organization": "Payment requests for \"{0}\" organization"**

**Comment by berkansasmaz** [comment]
Yes, I did not do it intentionally, because the key of localization will need to be changed and there are a few more places. I'll cover this in my next fix. Thank you again :)

**Review by ebicoglu — APPROVED** [review]

**Pull request merged**
