### PR TITLE
[8.3] Translated to Swedish (sv)

### PR DESCRIPTION
**Pull request by maliming**
https://github.com/abpframework/abp/issues/20864#issuecomment-2380351975

### CODE REVIEW

**Review by realLiangshiwei — APPROVED** [review]

**Comment by improwise** [comment]
@maliming Just created a new project using ABP 9 and there seem to be no traces of Swedish in there even though I know it was available in 8.X (at least I am pretty sure I saw Swedish being an option when I created a sample project)

image

Edit:

Seems like the activation on Swedish is missing, as in 

            options.Languages.Add(new LanguageInfo("sv", "sv", "Svenska"));

**Comment by maliming** [comment]
hi

I updated the `AbpLocalizationOptions
` then re-migrate the database.

image

**Comment by improwise** [comment]
> hi
> 
> I updated the `AbpLocalizationOptions ` then re-migrate the database.

Yes, this is what we did as mentioned above, but the necessary code for this to work should be included from get go and as you can see in the menu to the left, there are still translations missing as discussed in the other thread about this that I have since created. Probably best to use that one. Thanks.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/21473#issuecomment-2513441146

**Pull request merged**
