### PR TITLE
postgresql connection string updated

### PR DESCRIPTION
**Pull request by can-guven**
error : Keyword not supported: minimumpoolsize (Parameter 'keyword')

### CODE REVIEW

**Comment by maliming** [comment]
Can you check https://github.com/abpframework/abp/pull/7562

**Comment by can-guven** [comment]
I think you can use display name or property name as keyword.

These code are same for pool sizing:
Property Name Usage
` return "Host=localhost;Port=5432;Database=MyProjectName;User ID=root;Password=myPassword;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Connection Lifetime=0;";`

Display Name Usage 
` return "Host=localhost;Port=5432;Database=MyProjectName;User ID=root;Password=myPassword;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100;Connection Lifetime=0;";`

**Comment by maliming** [comment]
hi

We can keep it simple. developers can add `pool` config if needs.

**Review by maliming — APPROVED** [review]

**Comment by maliming** [comment]
@can-guven Thanks a lot.

**Pull request merged**
