### PR TITLE
CI test skip build and restore.

### PR DESCRIPTION
**Pull request by mehmetuken**
Ci have a problem testing process is ongoing. Maybe this solution fix it.

### CODE REVIEW

**Comment by ismcagdas** [comment]
@mehmetuken let's try and see 😄

**Comment by ismcagdas** [comment]
It seems like it is still problematic 

image

**Comment by maliming** [comment]
image

**Comment by ismcagdas** [comment]
It is better to disable it for now I guess.

**Comment by mehmetuken** [comment]
I test own local script its working. Ci haven't any error. We make one solution all modules and framework including just bulid and testing?

**Comment by mehmetuken** [comment]
I try many solutions but not run on github ci. Please disable or delete. Same tests its hanging but i cant find it.

**Comment by ismcagdas** [comment]
Deleted for now.

**Comment by mehmetuken** [comment]
@ismcagdas its releated #2075

**Pull request merged**
