### PR TITLE
Refactor the Permission Tree component's parent-child check feature.

### PR DESCRIPTION
**Pull request by mahmut-gundogdu**
Resolves https://github.com/volosoft/volo/issues/12751

Test steps.
Create abp app.
Go to identity/ Role or User.
Create new one.
Open permission modal.
Control all-parent-child related click. 

Expected behavior:
When user mark as check a parent, all children should be checked
when user mark as uncheck  a parent ,all children should be unchecked  
when user mark as check a child, parent should be checked.
when user mark as uncheck a last checked child, parent should be unchecked.

### CODE REVIEW

**Review by gizemmutukurt — APPROVED** [review]

**Comment by phil-enfom** [comment]
Hi @mahmut-gundogdu
The mentioned behaviour does not align with with what I posted on the Commercial Support Site.

I would like the behaviour for just the parent permission to be able to be selected which is possible in the MVC frontend but not the Angular.

If you tick the parent only the parent should activate, if you tick a child it should also tick the parent.

I am using the parent permission to grant read access to information then giving child permissions for Create, Edit, and Delete.

At the moment when you tick just the parent the system does not acknowledge the permssion has been ticked in the counts on the left and does not send it to the backend. If you do the same in the MVC frontend it is acknowledged and sent correctly.

Otherwise what is the point of having a permission that can not be granted on its own?

I would then have to add a Read Permission for every module as well as create edit and delete in which Create, Edit and Delete would also be dependant on.....

This current change would still end up with behaviour different from the MVC Frontend

**Comment by phil-enfom** [comment]
See #14551 and https://support.abp.io/QA/Questions/4111/Permission-not-granted-if-no-child-is-selected-UI---Repost-of-Github-Issue-14551

**Comment by phil-enfom** [comment]
**Test from Blazor Server**

Open Permissions:
image

Click Parent, Count changes to 1
image

Tick Child,m Count changes to 2
image

Untick Child, Count Decrements to 1
image

Tick Child then untick parent, Child unticks and Count Decrements to 0
image

**Comment by mahmut-gundogdu** [comment]
> See #14551 and https://support.abp.io/QA/Questions/4111/Permission-not-granted-if-no-child-is-selected-UI---Repost-of-Github-Issue-14551

yes, I made mistake. I have fixed. could you check the pr ? https://github.com/abpframework/abp/pull/14942

**Comment by mahmut-gundogdu** [comment]
I miss understand the behaviors of permissions-modal. The issue handled this branch again.https://github.com/abpframework/abp/pull/14942

**Pull request closed without merging**
