### PR TITLE
Revert Minio get blob stream

### PR DESCRIPTION
**Pull request by JadynWong**
fix: #10726

### CODE REVIEW

**Comment by charleszh-dev** [comment]
Hi, @JadynWong 
I added the `MinioBlobContainer_Tests` class to your branch, can you merge it? We can use it for unit testing, I tried it and the test failed.
微信截图_20211125142304

**Comment by JadynWong** [comment]
@realZhangChi 

I tested it locally.
image

**Comment by charleszh-dev** [comment]
@JadynWong 
Sorry, I checked out the dev branch. 😢

**Comment by charleszh-dev** [comment]
Hi, @maliming
I ran the unit tests and they all passed.
@JadynWong Thank you

**Review by maliming — APPROVED** [review]

**Pull request merged**
