### PR TITLE
Add Tencent cloud sms support

### PR DESCRIPTION
**Pull request by jiaguangli**
### Description

Add Tencent cloud sms support

### Checklist

- [ √ ] I fully tested it as developer / designer and created unit / integration tests
- [ √ ] I documented it (or no need to document or I will create a separate documentation issue)

### CODE REVIEW

**Review by maliming — APPROVED** [review]

**Comment by maliming** [comment]
It seems GitHub has a problem. @jiaguangli Can you cherry-pick commits and open a new Pull request?

screenshot-2024-12-17T17-08-05

**Comment by jiaguangli** [comment]
> It seems GitHub has a problem. @jiaguangli Can you cherry-pick commits and open a new Pull request?
> 
> screenshot-2024-12-17T17-08-05 [ screenshot-2024-12-17T17-08-05 ](https://private-user-images.githubusercontent.com/6908465/396431893-0c79f28d-d08f-4a6c-bc3a-45ce29ccfb87.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mjg4NDYsIm5iZiI6MTczNDQyODU0NiwicGF0aCI6Ii82OTA4NDY1LzM5NjQzMTg5My0wYzc5ZjI4ZC1kMDhmLTRhNmMtYmMzYS00NWNlMjljY2ZiODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDk0MjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAwZDEzZmNlMGIwMzc2ZjlhYzZiMGIzMDE1NTI1NjU2M2Y4OThkZDc1ZmZhNGMwYTNhNWM2MzA4MDY0MWY5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OxuEtR5ttUhN_RMLIx3QBNTwX3a-Eu2V5nFikPsKnIo) [ ](https://private-user-images.githubusercontent.com/6908465/396431893-0c79f28d-d08f-4a6c-bc3a-45ce29ccfb87.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mjg4NDYsIm5iZiI6MTczNDQyODU0NiwicGF0aCI6Ii82OTA4NDY1LzM5NjQzMTg5My0wYzc5ZjI4ZC1kMDhmLTRhNmMtYmMzYS00NWNlMjljY2ZiODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDk0MjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAwZDEzZmNlMGIwMzc2ZjlhYzZiMGIzMDE1NTI1NjU2M2Y4OThkZDc1ZmZhNGMwYTNhNWM2MzA4MDY0MWY5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OxuEtR5ttUhN_RMLIx3QBNTwX3a-Eu2V5nFikPsKnIo)

no

> It seems GitHub has a problem. @jiaguangli Can you cherry-pick commits and open a new Pull request?
> 
> screenshot-2024-12-17T17-08-05 [ screenshot-2024-12-17T17-08-05 ](https://private-user-images.githubusercontent.com/6908465/396431893-0c79f28d-d08f-4a6c-bc3a-45ce29ccfb87.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mjg5NTksIm5iZiI6MTczNDQyODY1OSwicGF0aCI6Ii82OTA4NDY1LzM5NjQzMTg5My0wYzc5ZjI4ZC1kMDhmLTRhNmMtYmMzYS00NWNlMjljY2ZiODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDk0NDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDYzMDUwZGQyYTZhOTY2Mzk1YTZlMWIwZTc4Zjc4NjI4ZjMxM2ViMDNhYjYxMGE2NTgzZTE4ZjkwNjU0NjViZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AnRiFM3KNjsTNLB1pwLn4ZW7imK4q68DBWptGa9q484) [ ](https://private-user-images.githubusercontent.com/6908465/396431893-0c79f28d-d08f-4a6c-bc3a-45ce29ccfb87.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mjg5NTksIm5iZiI6MTczNDQyODY1OSwicGF0aCI6Ii82OTA4NDY1LzM5NjQzMTg5My0wYzc5ZjI4ZC1kMDhmLTRhNmMtYmMzYS00NWNlMjljY2ZiODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDk0NDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDYzMDUwZGQyYTZhOTY2Mzk1YTZlMWIwZTc4Zjc4NjI4ZjMxM2ViMDNhYjYxMGE2NTgzZTE4ZjkwNjU0NjViZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AnRiFM3KNjsTNLB1pwLn4ZW7imK4q68DBWptGa9q484)

no problem

**Comment by jiaguangli** [comment]
> It seems GitHub has a problem. @jiaguangli Can you cherry-pick commits and open a new Pull request?
> 
> screenshot-2024-12-17T17-08-05 [ screenshot-2024-12-17T17-08-05 ](https://private-user-images.githubusercontent.com/6908465/396431893-0c79f28d-d08f-4a6c-bc3a-45ce29ccfb87.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mjg5NTksIm5iZiI6MTczNDQyODY1OSwicGF0aCI6Ii82OTA4NDY1LzM5NjQzMTg5My0wYzc5ZjI4ZC1kMDhmLTRhNmMtYmMzYS00NWNlMjljY2ZiODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDk0NDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDYzMDUwZGQyYTZhOTY2Mzk1YTZlMWIwZTc4Zjc4NjI4ZjMxM2ViMDNhYjYxMGE2NTgzZTE4ZjkwNjU0NjViZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AnRiFM3KNjsTNLB1pwLn4ZW7imK4q68DBWptGa9q484) [ ](https://private-user-images.githubusercontent.com/6908465/396431893-0c79f28d-d08f-4a6c-bc3a-45ce29ccfb87.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mjg5NTksIm5iZiI6MTczNDQyODY1OSwicGF0aCI6Ii82OTA4NDY1LzM5NjQzMTg5My0wYzc5ZjI4ZC1kMDhmLTRhNmMtYmMzYS00NWNlMjljY2ZiODcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDk0NDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDYzMDUwZGQyYTZhOTY2Mzk1YTZlMWIwZTc4Zjc4NjI4ZjMxM2ViMDNhYjYxMGE2NTgzZTE4ZjkwNjU0NjViZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AnRiFM3KNjsTNLB1pwLn4ZW7imK4q68DBWptGa9q484)

no problem

**Comment by maliming** [comment]
Thanks @jiaguangli 👍

**Pull request merged**
