### PR TITLE
Rebus Integration for Distributed Event Bus

### LINKED ISSUE #376: Consider Rebus Integration for Distributed Event Bus

### PR DESCRIPTION
**Pull request by realLiangshiwei**
Resolve https://github.com/abpframework/abp/issues/376

### CODE REVIEW

**Review by hikalkan — APPROVED** [review]

**Comment by hikalkan** [comment]
@maliming can you review & merge this. I will create a new issue to you to test this.

**Comment by maliming** [comment]
Ok no problem.

**Comment by maliming** [comment]
Github CI check failed.

**Review by maliming — CHANGES_REQUESTED** [review]
Github CI check failed.

**Comment by realLiangshiwei** [comment]
@maliming  Resolved

**Pull request merged**
