### PR TITLE
add object value :book:

### PR DESCRIPTION
**Pull request by yanghaiji**
Add a description of the value object

### CODE REVIEW

**Comment by realLiangshiwei** [comment]
Thanks a lot．@yanghaiji

Can you follow [this document](https://docs.abp.io/en/abp/latest/Value-Objects) for translation?

**Comment by rqx110** [comment]
Java code?

**Comment by yanghaiji** [comment]
> Java code?

yes

**Comment by yanghaiji** [comment]
> Thanks a lot．@yanghaiji
> 
> Can you follow [this document](https://docs.abp.io/en/abp/latest/Value-Objects) for translation?

OK

**Comment by rqx110** [comment]
> > Java code?
> 
> yes

this is a c# framework, not java!!!!

**Review by realLiangshiwei — APPROVED** [review]

**Pull request merged**
