### PR TITLE
Cli create app template without ui.

### LINKED ISSUE #1982: Add cli app template --ui none option.
This option create just httpapi.host project app template without ui.

### PR DESCRIPTION
**Pull request by mehmetuken**
Resolve #1982

--ui none --separate-identity-server (seperate host and identityserver)
--ui none (hostwithids)

### CODE REVIEW

**Comment by hikalkan** [comment]
@maliming @mehmetuken is this same of https://github.com/abpframework/abp/pull/1993 ?
I already merged #1993, but this seems makes more.
What should I do?

**Comment by maliming** [comment]
I will handle this PR and documentation.

**Comment by mehmetuken** [comment]
Because @maliming solution not create seperated identity server not work well it's remove hostwithids project always. I use angular ui and no ui code together.

**Comment by maliming** [comment]
hi @mehmetuken 
I can't access your repository to test this PR.

image

**Comment by mehmetuken** [comment]
hi @maliming 
I deleted my forks sorry. You can test here: https://github.com/mehmetuken/abp/tree/cli-none-ui

**Comment by maliming** [comment]
Move to https://github.com/abpframework/abp/pull/2157

**Pull request closed without merging**
