### PR TITLE
feat: make some components replaceable

### LINKED ISSUE #2404: Making Angular components replaceable

### PR DESCRIPTION
**Pull request by mehmet-erim**
Closes #2404

### CODE REVIEW

**Comment by HenroOnline** [comment]
I've used this technic for creating a custom Personal Settings component which works fine. 
However when I try to create a custom Registration component I get this error:

**Error**
<code>
compiler.js:2175 Uncaught Error: Template parse errors:
Can't bind to 'mainContentRef' since it isn't a known property of 'abp-auth-wrapper'.
1. If 'abp-auth-wrapper' is an Angular component and it has 'mainContentRef' input, then verify that it is part of this module.
2. If 'abp-auth-wrapper' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    }
  }"
                  [ERROR ->][mainContentRef]="mainContentRef">
</abp-auth-wrapper>
<ng-template #mainContentRef>
"): ng:///AppModule/CustomRegisterComponent.html@6:18
'abp-auth-wrapper' is not a known element:
1. If 'abp-auth-wrapper' is an Angular component, then verify that it is part of this module.
2. If 'abp-auth-wrapper' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<abp-auth-wrapper *abpReplaceableTemplate="{
    componentKey: 'Account.AuthWrapperComponent',
    "): ng:///AppModule/CustomRegisterComponent.html@0:0
    at syntaxError (compiler.js:2175)
    at TemplateParser.parse (compiler.js:11388)
    at JitCompiler._parseTemplate (compiler.js:25963)
    at JitCompiler._compileTemplate (compiler.js:25951)
    at compiler.js:25895
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:25895)
    at compiler.js:25808
    at Object.then (compiler.js:2166)
    at JitCompiler._compileModuleAndComponents (compiler.js:25807)
</code>


**Custom component registration**
<code>
    this.store.dispatch(
      new AddReplaceableComponent({
        component: CustomPersonalSettingsComponent,
        key: 'Account.PersonalSettingsComponent'
      }),
    );
</code>

For the custom registration component I copied the .html and .ts file from the framework and only changed selector and templateUrl in the .ts file.

Any clues on what I am doing wrong?

**Comment by mehmet-erim** [comment]
Hello @HenroOnline 

You can't use the lazy module specific components in your components. Lazy modules can't use the like a `SharedModule`.  `AuthWrapperComponent` cannot be exported from `AccountModule`. 

Remove the `abp-auth-wrapper` selector from your template and try again. You will see that it works.

**Comment by HenroOnline** [comment]
@mehmet-erim Thanks. Removing the AuthWrapperComponent and the surrounding <ng-template #mainContentRef>tag resolved the issue.

**Comment by HenroOnline** [comment]
Another question. Replacing the register component now works. But my validation messages are not visible (like required field). I copied the register.component.html and register.component.ts, removed the abp-auth-wrapper and template tags around.

Without further changes no error messages are shown, the form is still validated and the form is not submitted until the username, email and password fields are filled in correct.

When I disable the component replacement I see that with the original register component <abp-validation-error> elements are placed under the fields that are not valid. This does not happen now. 

Any thoughts about it?

**Comment by mehmet-erim** [comment]
@HenroOnline we use the [`ngx-validate`](https://github.com/ng-turkey/ngx-validate) package for validation. I am one of the maintainers of this package.

[See the implementation](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/theme-basic/src/lib/theme-basic.module.ts#L27)

**Comment by HenroOnline** [comment]
Thanks. Importing NgxValidateCoreModule did fix the problem.

**Comment by MohamedElyamani** [comment]
hi
i am using free edition angular and abp version 8.0.2
and i want to add new input field in tenant box
it present me a tenant name and password for example i want to add new input named CRN for example
i used this way in repo but not work
so how to make it
in back end in this path (src/ef/extensionMapping) 
and add this
 OneTimeRunner.Run(() =>
 {
     ObjectExtensionManager.Instance
         .MapEfCoreProperty<Tenant, string>(
         "CRN",
         (entityBuilder, propertyBuilder) =>
         {
             propertyBuilder.HasMaxLength(250);
         }
         );
 });
 how to make thid visible in angular i do not have the original tenant html component

**Pull request merged**
