### PR TITLE
Extend StandardMenus with nested static classes per StandardLayouts

### LINKED ISSUE #16305: Pushing Menu Items from module to other layouts
StandardMenus must cover other layouts (application, account, public)
Where we have a module with multi layout menus we need to access to shared menu names. For example a product module has management menus and public menus. 
```C#
public static class StandardMenus
{
    public static class Application
    {
        public const string Main = "Application.Main";
        public const string User = "Application.User";
        public const string Shortcut = "Application.Shortcut";
        public const string Footer = "Application.Footer";
    }
    
    public static class Public
    {
        public const string Main = "Public.Main";
        public const string User = "Public.User";
        public const string Shortcut = "Public.Shortcut";
        public const string Footer = "Public.Footer";
    }
    
    public static class Account
    {
        public const string Main = "Account.Main";
        public const string User = "Account.User";
        public const string Shortcut = "Account.Shortcut";
        public const string Footer = "Account.Footer";
    }
}
```
footer menu can be used for shortcuts or site maps. it's a suggestion

I can create a PR for this. The problem is the Commercial modules/templates.

### PR DESCRIPTION
**Pull request by hitaspdotnet**
### Description

Resolves #16305 

This PR is extending `StandardMenus` with nested static classes per `StandardLayouts` with extra `Footer` menu name.

### Checklist

- [x] I fully tested it as theme developer / designer with Mvc app template
- [x] I documented it (need to document in other cultures)

### How to test it?
```pwsh
abp new Acme.BookStore -t app -ts "PathToAbpLocalRepo\templates\app" --local-framework-ref --abp-path "PathToAbpLocalRepo"
```

### CODE REVIEW

**Comment by maliming** [comment]
hi @hikalkan 

Is this was your expected?

image

**Comment by hikalkan** [comment]
Thanks. Since this is a breaking change, I will carefully think on it.

**Comment by hitaspdotnet** [comment]
@hikalkan we can set application menus without prefix to avoid breaks.
```csharp
    public static class Application
    {
        public const string Main = "Main";
        public const string User = "User";
        public const string Shortcut = "Shortcut";
        public const string Footer = "Footer";
    }

    public static class Public
    {
        public const string Main = "Public.Main";
        public const string User = "Public.User";
        public const string Shortcut = "Public.Shortcut";
        public const string Footer = "Public.Footer";
    }

    public static class Account
    {
        public const string Main = "Account.Main";
        public const string User = "Account.User";
        public const string Shortcut = "Account.Shortcut";
        public const string Footer = "Account.Footer";
    }
```

**Comment by hikalkan** [comment]
We don't want to introduce such a breaking change.

**Pull request closed without merging**
