### PR TITLE
Add `PermissionsRequirement` and `PermissionsRequirementHandler` to check multiple permissions.

### LINKED ISSUE #10151: Add `PermissionsRequirement` and `PermissionsRequirementHandler` to check multiple permissions.
https://github.com/abpframework/abp/pull/10150#issuecomment-927311890

### PR DESCRIPTION
**Pull request by maliming**
Resolve #10151

```cs
[Authorize("TestPermission1_And_TestPermission2")]
public ActionResult Custom_And_PolicyTest()
{
    return Content("OK");
}

[Authorize("TestPermission1_Or_TestPermission2")]
public ActionResult Custom_Or_PolicyTest()
{
    return Content("OK");
}


context.Services.AddAuthorization(options =>
{
    options.AddPolicy("TestPermission1_And_TestPermission2", policy =>
    {
        policy.Requirements.Add(new PermissionsRequirement(new []{"TestPermission1", "TestPermission2"}, requiresAll: true));
    });

    options.AddPolicy("TestPermission1_Or_TestPermission2", policy =>
    {
        policy.Requirements.Add(new PermissionsRequirement(new []{"TestPermission1", "TestPermission2"}, requiresAll: false));
    });
});
```

### CODE REVIEW

**Comment by MrChuJiu** [comment]
I don't think it's an ok introduction. If you can, you should start with IPermissionDefinitionContext

**Comment by maliming** [comment]
This has nothing to do with `IPermissionDefinitionContext`.

**Comment by MrChuJiu** [comment]
> This has nothing to do with `IPermissionDefinitionContext`.

Is the handwritten policy a little difficult to maintain

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/10150#issuecomment-927311890

**Comment by MrChuJiu** [comment]
> See [#10150 (comment)](https://github.com/abpframework/abp/pull/10150#issuecomment-927311890)

I see. Thank you

**Comment by netcore-jroger** [comment]
It is believed that this realization increases the workload. I don't like this way of implementation.

**Comment by maliming** [comment]
We try our best not to break or change Microsoft's design, otherwise, it may conflict with third-party libraries.

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-5.0

**Comment by gdlcf88** [comment]
Another way to implement a complex permission check.

```CSharp
public Task MyAction1Async()
{
    await CheckMyAction1PolicyAsync();
    // ...
}

public Task MyAction2Async()
{
    await CheckMyAction2PolicyAsync();
    // ...
}

public Task MyAction3Async()
{
    await CheckMyAction3PolicyAsync();
    // ...
}

private Task CheckMyAction1PolicyAsync()
{
    // requires Permission1 and Permission2
    await AuthorizationService.CheckAsync("Permission1");
    await AuthorizationService.CheckAsync("Permission2");
}

private Task CheckMyAction2PolicyAsync()
{
    // requires Permission1 or Permission2
    if (!await AuthorizationService.IsGrantedAnyAsync("Permission1", "Permission2"))
    {
        throw new AbpAuthorizationException("my code");
    }
}

private Task CheckMyAction3PolicyAsync()
{
    // requires (Permission1 or Permission2) and Permission3
    if (!await AuthorizationService.IsGrantedAnyAsync("Permission1", "Permission2") ||
        !await AuthorizationService.IsGrantedAsync("Permission3"))
    {
        throw new AbpAuthorizationException("my code");
    }
}
```

**Comment by netcore-jroger** [comment]
> We try our best not to break or change Microsoft's design, otherwise, it may conflict with third-party libraries.
> 
> https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-5.0

All right. so be it.
Based on role is to use comma separated.
So I still choose to implemented in my way.
Because it is very simple and also follows the design of Microsoft.

**Comment by netcore-jroger** [comment]
> Another way to implement a complex permission check.
> 
> ```CSharp
> public Task MyAction1Async()
> {
>     await CheckMyAction1PolicyAsync();
>     // ...
> }
> 
> public Task MyAction2Async()
> {
>     await CheckMyAction2PolicyAsync();
>     // ...
> }
> 
> public Task MyAction3Async()
> {
>     await CheckMyAction3PolicyAsync();
>     // ...
> }
> 
> private Task CheckMyAction1PolicyAsync()
> {
>     // requires Permission1 and Permission2
>     await AuthorizationService.CheckAsync("Permission1");
>     await AuthorizationService.CheckAsync("Permission2");
> }
> 
> private Task CheckMyAction2PolicyAsync()
> {
>     // requires Permission1 or Permission2
>     if (!await AuthorizationService.IsGrantedAnyAsync("Permission1", "Permission2"))
>     {
>         throw new AbpAuthorizationException("my code");
>     }
> }
> 
> private Task CheckMyAction3PolicyAsync()
> {
>     // requires (Permission1 or Permission2) and Permission3
>     if (!await AuthorizationService.IsGrantedAnyAsync("Permission1", "Permission2") ||
>         !await AuthorizationService.IsGrantedAsync("Permission3"))
>     {
>         throw new AbpAuthorizationException("my code");
>     }
> }
> ```

This invades the business logic and is not recommended.

**Review by realLiangshiwei — APPROVED** [review]

**Pull request merged**
