### PR TITLE
Update `OpenIddict` to `5.5.0`.

### LINKED ISSUE #19620: Update `OpenIddict` to latest(5.5.0)
https://github.com/openiddict/openiddict-core/releases/tag/5.5.0

### PR DESCRIPTION
**Pull request by maliming**
Resolve #19620

I have tested the `OpenID Connect` login.

### CODE REVIEW

**Comment by hikalkan** [comment]
Can we move this to 8.2?

**Comment by kevinchalet** [comment]
Hey,

Hope you're doing well 👋🏻 

FYI, OpenIddict 5.5.0 - released yesterday - still targets IdentityModel 7.4.1 (with all the bugs recently caused by mismatched IdentityModel package versions, I'm now a bit reluctant to bump them 😅).

I see that your `Directory.Packages.props` references the 7.5.1 version: if it's not already the case, I encourage you to to add explicit, direct references to IdentityModel 7.5.1 in the projects that depend on OpenIddict or the MSFT OIDC or JWT handlers, to avoid any IM version mismatch (which always results in very weird, super hard-to-find bugs 😅)

Here's the 3 IM packages OpenIddict 5.5.0 references: https://github.com/openiddict/openiddict-core/blob/5.5.0/Directory.Packages.props#L334-L336

All the best.

**Comment by maliming** [comment]
Thanks @kevinchalet 

We have used the latest(7.5.1) packages in `MSFT OIDC and JWT` projects.

**Comment by kevinchalet** [comment]
> We have used the latest(7.5.1) packages in `MSFT OIDC and JWT` projects.

👍🏻 

(I'll likely bump IdentityModel in the next OpenIddict version, once we're sure there's no weird thing happening 🤣)

**Comment by maliming** [comment]
> Can we move this to 8.2?

I have changed the target to `prerel-8.2`.

**Review by salihozkara — APPROVED** [review]

**Pull request merged**
