### PR TITLE
Cli create app template without ui. 

### LINKED ISSUE #1982: Add cli app template --ui none option.
This option create just httpapi.host project app template without ui.

### PR DESCRIPTION
**Pull request by maliming**
Resolve #1982

--ui none --separate-identity-server (seperate host and identityserver)
--ui none (hostwithids)

### CODE REVIEW

**Comment by maliming** [comment]
@mehmetuken 
Since your repository has permissions issues, I recreate the branch and merge it. Thanks!

**Comment by mehmetuken** [comment]
Thanks.

**Comment by 274188A** [comment]
is this a first step towards making Blazor tech usable with Abp?

**Comment by maliming** [comment]
@274188A 
This is the first step for all spa applications. : )

**Comment by hikalkan** [comment]
I think creating an angular template and deleting the angular folder is same. Then you can create any UI you like. If deleting the angular folder takes too much time, I can help you 😄

**Pull request merged**
