### PR TITLE
Blogs member page updated, space added

### PR DESCRIPTION
**Pull request by honurbu**
Resolve : https://github.com/volosoft/vs-internal/issues/3417

image

### CODE REVIEW

**Review by salihozkara — APPROVED** [review]

**Comment by gizemmutukurt** [comment]
Name part is too big
image

**Review by gizemmutukurt — CHANGES_REQUESTED** [review]
Name part is too big
image

**Comment by honurbu** [comment]
image

**Review by gizemmutukurt — APPROVED** [review]

**Comment by ebicoglu** [comment]
image

**Comment by honurbu** [comment]
image

image

**Comment by honurbu** [comment]
https://github.com/abpframework/abp/pull/18594

**Pull request merged**
