### PR TITLE
CMS Kit Enhancements

### LINKED ISSUE #17587: CMS Kit: Enhancement ideas for some features
While working on https://github.com/abpframework/abp/issues/17555, I have taken notes on some enhancement ideas for some features in the CMS Kit Module and wanted to create an issue, so we can consider making the related improvements. You can see the following sections for enhancement ideas by each feature:

<details>
<summary><h2>Blogging Feature</h2></summary>

> https://docs.abp.io/en/abp/latest/Modules/Cms-Kit/Blogging

* We have a hard-coded blog prefix, which is *blogs*. So, whenever we create a blog, the URL becomes something like */blogs/{{blog-name}}*, I think this is a restriction, we can allow users to set another prefix or they might want to have just single blog and in that case the *blogs* prefix is completely make no sense.

https://github.com/abpframework/abp/blob/bda231b319b62582dee4f8389494cd4442ac474f/modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPublicWebModule.cs#L94-L95

> We can define a const for blog prefixes as we did in the Blogging Module:

* The blog homepage has a select box that allows us to filter blog posts by authors. This can be optional, so we can add a checkbox on features modal to make it enable/disable on runtime. Also, "searching by tag" feature would be good on homepage (if it's enabled) because otherwise the only place that we can see posts by tags is in the footer of the blog post.

image

* Also, we should completely revise the blog post page because it has some virtual problems on the basic-theme (especially if we enable tagging & comment features). 

</details>

---

<details>
<summary><h2>Page Feature</h2></summary>

> https://docs.abp.io/en/abp/latest/Modules/Cms-Kit/Pages

* We can consider allowing a `/` character in the slug while creating a page. A page URL might be like *"products/product-1" but in the current design it replaces the `/` character with an empty string and it's not possible to use such a URL.
</details>

### PR DESCRIPTION
**Pull request by enisn**
### Description

Resolves https://github.com/abpframework/abp/issues/17587

- `blogs` prefix can be customized, check the address bar below, it's configured as `foo`
  image
- Tag filtering is displayed at the top of the page when filtered by clicking on it
  image
- Also same for author filtering. It's not visible until applying a filtering. _(A filter feature can be added to show them by default)_
  image

- Added readonly support for **Comments** & **Ratings** components
  - Comments:
      ```csharp
      @await Component.InvokeAsync(typeof(CommentingViewComponent), new
      {
        entityType = "Product",
        entityId = "...",
        isReadOnly = true,
        referralLinks  = new [] {"nofollow"}
      })
      ```

  - Ratings
    ```csharp
    @await Component.InvokeAsync(typeof(RatingViewComponent), new
    {
      entityType = "Product",
      entityId = "entityId",
      isReadOnly = true
    })
    ```

### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Please describe how this can be tested by the test engineers if it is not already explicit - or remove this section if no need to description.

### CODE REVIEW

**Review by EngincanV — APPROVED** [review]

**Comment by enisn** [comment]
Codecov couldn't be run again in this PR, but if you visit the codecov you can see this PR even increases test coverage:

image

**Comment by gizemmutukurt** [comment]
- [x] Leptonx appears broken in the theme.
image


- [x] In Lepton theme, when the tags text is white, the tags cannot be read.

(https://github.com/volosoft/volo/issues/15570#issuecomment-1782565355)
image

**Review by gizemmutukurt — CHANGES_REQUESTED** [review]
https://github.com/volosoft/lepton/issues/1764
https://github.com/volosoft/volo/issues/15570
It will be checked again when the relevant error issues are fixed.

**Comment by enisn** [comment]
> [volosoft/lepton#1764](https://github.com/volosoft/lepton/issues/1764) [volosoft/volo#15570](https://github.com/volosoft/volo/issues/15570) It will be checked again when the relevant error issues are fixed.

Both are solved

**Comment by salihozkara** [comment]
- [ ]  If there is no selected author, the author selection option does not appear

[Untitled_ Nov 02,2023 09_42 AM.webm](https://github.com/abpframework/abp/assets/58659931/7e043909-3be7-4cb5-9f66-78d93d71848d)

- [x]  Looks broken in basic theme
image

**Comment by enisn** [comment]
> * [ ]   If there is no selected author, the author selection option does not appear

We hide it on purpose, it was staying at the top alone meaningless

**Comment by enisn** [comment]
@salihozkara 
I updated both Delete button & TOC design


image

---

image

**Review by salihozkara — APPROVED** [review]

**Pull request merged**
