### PR TITLE
Cli: Enahncement related with LeptonX

### PR DESCRIPTION
**Pull request by yekalkan**

### CODE REVIEW

**Comment by ebicoglu** [comment]
@gizemmutukurt needs testing...

**Comment by gizemmutukurt** [comment]
Error while creating project

image

**Log:**

```
`2022-10-07 14:22:17.879 +03:00 [INF] Executed endpoint 'Volo.Abp.Suite.Controllers.AbpSuiteController.IsSuitePreviewAsync (Volo.Abp.Suite)'
2022-10-07 14:22:17.879 +03:00 [INF] Request finished HTTP/1.1 GET http://localhost:3000/api/abpSuite/is-suite-preview application/json - - 200 - application/json;+charset=utf-8 14.6884ms
2022-10-07 14:24:45.654 +03:00 [INF] Request starting HTTP/1.1 POST http://localhost:3000/api/abpSuite/createSolution application/json 594
2022-10-07 14:24:45.654 +03:00 [INF] Executing endpoint 'Volo.Abp.Suite.Controllers.AbpSuiteController.CreateSolutionAsync (Volo.Abp.Suite)'
2022-10-07 14:24:45.655 +03:00 [INF] Route matched with {action = "CreateSolution", controller = "AbpSuite", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Suite.Models.Solution] CreateSolutionAsync(Volo.Abp.Suite.Models.CreateSolutionModel) on controller Volo.Abp.Suite.Controllers.AbpSuiteController (Volo.Abp.Suite).
2022-10-07 14:24:45.659 +03:00 [INF] Creating your project...
2022-10-07 14:24:45.659 +03:00 [INF] Project name: TestPR
2022-10-07 14:24:45.659 +03:00 [INF] Template: app-pro
2022-10-07 14:24:45.659 +03:00 [INF] Preview: yes
2022-10-07 14:24:45.986 +03:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}

2022-10-07 14:24:45.996 +03:00 [ERR] You can only create a new preview solution with preview CLI version. Update your ABP CLI to the preview version.
Volo.Abp.Cli.CliUsageException: You can only create a new preview solution with preview CLI version. Update your ABP CLI to the preview version.
   at Volo.Abp.Cli.Commands.ProjectCreationCommandBase.GetProjectBuildArgsAsync(CommandLineArgs commandLineArgs, String template, String projectName) in C:\GitHub\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\ProjectCreationCommandBase.cs:line 86
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in C:\GitHub\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 88
   at Volo.Abp.Suite.Areas.AbpSuite.CrudPageGenerator.Services.SolutionService.CreateSolutionAsync(CreateSolutionModel input) in C:\GitHub\volo\abp\suite\src\Volo.Abp.Suite\Areas\AbpSuite\CrudPageGenerator\Services\SolutionService.cs:line 462
   at lambda_method1722(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, `
```

**Comment by yekalkan** [comment]
> Error while creating project

Fixed. (It was occuring on only development environment)

**Comment by gizemmutukurt** [comment]
Test is ok.

image

**Review by gizemmutukurt — APPROVED** [review]

**Review by ebicoglu — APPROVED** [review]

**Pull request merged**
