### PR TITLE
DataGrid improvements

### LINKED ISSUE #7926: Improve blazor data table on empty tables
See the table below:

image

Two problems here;

1. `1 - 0 of 0 items` is wrong. I believe it should be `0 - 0 of 0 items` or `no items`.
2. It is better to write "No data available" in the table in case of empty. Otherwise, I suspect that it is still being loaded. Example (from MVC UI):

image

Also, a loading indicator would be nice.

### PR DESCRIPTION
**Pull request by stsrki**
resolves #7926

- Fixed "no items" text
- Added loading indicator
- Added empty data template
- Bundled global files

Tested on the basic theme for Blazor WebAssembly and Blazor Server projects.

### CODE REVIEW

**Comment by hikalkan** [comment]
@ilkayilknur can you review & test this please?

**Comment by ilkayilknur** [comment]
@stsrki Did you push updates to the Volo repo?

**Comment by stsrki** [comment]
> @stsrki Did you push updates to the Volo repo?

It's a draft on https://github.com/volosoft/volo/pull/6650 since I have some trouble with the global bundle for lepton themes

**Review by ilkayilknur — APPROVED** [review]
I tested with open-source templates and looks good to me. 
I will merge the PR when the bundling issue is resolved on the volo side.

**Review by cotur — APPROVED** [review]

**Pull request merged**
