### PR TITLE
Updated docs for next and previous buttons

### PR DESCRIPTION
**Pull request by honurbu**
Resolves https://github.com/volosoft/vs-internal/issues/3749

Web Applications (Layered Architecture)
Web Applications (Single-Layered Architecture)
Web Applications Development

JSON was added to these documents to access previous and next documentation.

For Commercial Documents use this branch => https://github.com/abpio/abp-commercial-docs/pull/747

### CODE REVIEW

**Comment by gizemmutukurt** [comment]
- [ ] 404 errors are received in the tuorials section of the commercial document.
Apex_1708317940550

- [ ] The word "part" was not included in the other rankings. Was it specifically preferred?
image

**Review by gizemmutukurt — CHANGES_REQUESTED** [review]
will be checked again when the problems are fixed

**Comment by gizemmutukurt** [comment]
It is also clickable outside of written areas. It should only be clickable when on the next, previous button and title. (abp and volo document)  , https://github.com/abpframework/abp/issues/19074
image

**Review by gizemmutukurt — CHANGES_REQUESTED** [review]
will be checked again after the change

**Review by gizemmutukurt — APPROVED** [review]

**Comment by honurbu** [comment]
https://github.com/abpframework/abp/pull/19107

**Pull request merged**
