### PR TITLE
Blazor UI : Message service document improvements

### PR DESCRIPTION
**Pull request by ilkayilknur**

### CODE REVIEW

**Comment by hikalkan** [comment]
I suppose there is a options class for global configuration, just [like the notification](https://github.com/abpframework/abp/blob/rel-4.0/docs/en/UI/Blazor/Notification.md#global-configuration).
@stsrki ?

**Comment by ilkayilknur** [comment]
The related issue is in the backlog  https://github.com/abpframework/abp/issues/5742 @hikalkan

**Comment by hikalkan** [comment]
Thanks @ilkayilknur 👍

**Comment by stsrki** [comment]
@hikalkan It's going to be soon.

**Pull request merged**
