### PR TITLE
Fixed mongo repository expression error in AuditLogging module.

### PR DESCRIPTION
**Pull request by maliming**
MongoDB.Driver's `GroupBy` method cannot translate `DateTime.Property`.
eg `GroupBy(t => ExecutionTime.Date)`

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks @maliming. But this will have a performance problem since it brings all audit logs into memory and group in the code.
Can you search on that how we can implement this in MongoDB. We can use Mongo's own API (instead of LINQ), no problem.

**Comment by maliming** [comment]
I will check it again.

**Comment by hikalkan** [comment]
Should I merge now?

**Comment by maliming** [comment]
@hikalkan Yes.

**Comment by hikalkan** [comment]
Thanks @maliming

**Pull request merged**
